// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"
)

const isEmailSuppressed = `-- name: IsEmailSuppressed :one

SELECT EXISTS(
    SELECT 1 FROM gateway.email_suppressions
    WHERE email = $1 AND workspace_id = $2
)
`

type IsEmailSuppressedParams struct {
	Email       string
	WorkspaceID string
}

// Gateway email suppression queries
func (q *Queries) IsEmailSuppressed(ctx context.Context, arg IsEmailSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailSuppressed, arg.Email, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const storeSuppression = `-- name: StoreSuppression :exec
INSERT INTO gateway.email_suppressions (email, workspace_id, remote_ip)
VALUES ($1, $2, $3)
ON CONFLICT (email, workspace_id) DO UPDATE
    SET user_id   = current_setting('request.user_id', true),
        remote_ip = EXCLUDED.remote_ip
`

type StoreSuppressionParams struct {
	Email       string
	WorkspaceID string
	RemoteIp    string
}

func (q *Queries) StoreSuppression(ctx context.Context, arg StoreSuppressionParams) error {
	_, err := q.db.Exec(ctx, storeSuppression, arg.Email, arg.WorkspaceID, arg.RemoteIp)
	return err
}
