/**
 * CSV Parser
 *
 * Parses CSV files for file artifacts.
 */

import { readFile } from "node:fs/promises";
import Papa from "papaparse";
import { z } from "zod";

export type CsvCell = string | number | boolean | null;

export interface CsvParseResult {
  data: Array<Record<string, CsvCell>>;
  columns: string[];
  rowCount: number;
}

export const CsvParseResultSchema = z.object({
  data: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
  columns: z.array(z.string()),
  rowCount: z.number().int().nonnegative(),
});

const MAX_HEADER_SCAN_LINES = 10;

/**
 * Find the first valid header line in CSV content, skipping garbage lines
 */
function findHeaderLine(content: string): string {
  const lines = content.split("\n");

  for (let i = 0; i < Math.min(lines.length, MAX_HEADER_SCAN_LINES); i++) {
    const line = lines[i]?.trim();
    if (!line) continue;

    const values = line.split(",").map((v) => v.trim().replace(/^"|"$/g, ""));
    const nonEmptyCount = values.filter((v) => v !== "").length;
    const hasAutoGeneratedNames = values.some((v) => /^_\d+$/.test(v));

    // Valid header: mostly populated, no auto-generated names
    if (nonEmptyCount >= values.length / 2 && !hasAutoGeneratedNames) {
      return lines.slice(i).join("\n");
    }
  }

  return content;
}

/**
 * Parse a CSV file from the given file path.
 */
export async function parseCsv(filePath: string): Promise<CsvParseResult> {
  const rawContent = await readFile(filePath, "utf-8");
  const content = findHeaderLine(rawContent);

  const parsed = Papa.parse<Record<string, CsvCell>>(content, {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: "greedy",
    transformHeader: (header: string) => header.trim(),
  });

  if (!parsed.meta.fields || parsed.meta.fields.length === 0) {
    throw new Error(`CSV file ${filePath} has no header row or columns`);
  }

  // Filter out rows where all values are null/empty
  const data = parsed.data.filter((row: Record<string, CsvCell>) => {
    const values = Object.values(row);
    return values.some((v) => v !== null && v !== "" && v !== undefined);
  });

  const columns = parsed.meta.fields as string[];

  return { data, columns, rowCount: data.length };
}
