displayName: ExtractUserID Plugin
type: middleware

import: github.com/tempestteam/traefik/extractuserid

summary: 'ExtractUserID is a middleware that validates JWT tokens and extracts the user ID as a hex-encoded header.'

testData:
  ExtractUserID:
    CookieName: "tempest_token"
    JWTPublicKey: "/secrets/app/jwt-public-key-pem"
    HeaderName: "X-Atlas-User-ID"
