import { z } from "zod";

// Credential type enum
export const CredentialTypeSchema = z.enum(["apikey", "oauth"]);

/**
 * OAuth credential secret schema.
 * Stores OAuth tokens with optional refresh and expiration metadata.
 */
const OAuthCredentialSecretSchema = z.object({
  access_token: z.string(),
  refresh_token: z.string().optional(),
  token_type: z.string().default("Bearer"),
  expires_at: z.number().optional(), // Unix timestamp (seconds)
  granted_scopes: z.array(z.string()).optional(), // what was actually authorized
  client_id: z.string().optional(), // for dynamic OAuth refresh
});

// Metadata - timestamps for credential lifecycle tracking
const MetadataSchema = z.object({ createdAt: z.iso.datetime(), updatedAt: z.iso.datetime() });
export type Metadata = z.infer<typeof MetadataSchema>;

// What gets stored and retrieved
export const CredentialSchema = z.object({
  id: z.string(),
  type: CredentialTypeSchema,
  provider: z.string(), // "openai", "github", etc.
  label: z.string(), // user-friendly name
  secret: z.record(z.string(), z.unknown()),
  metadata: MetadataSchema,
});

export type Credential = z.infer<typeof CredentialSchema>;

/**
 * OAuth credential schema for credentials obtained via OAuth flow.
 */
const OAuthCredentialSchema = z.object({
  id: z.string(),
  type: z.literal("oauth"),
  provider: z.string(),
  userIdentifier: z.string(), // email, sub, or account ID
  label: z.string(),
  secret: OAuthCredentialSecretSchema,
  metadata: MetadataSchema,
});

export type OAuthCredential = z.infer<typeof OAuthCredentialSchema>;

// What you get when LISTING (no secrets)
export const CredentialSummarySchema = CredentialSchema.omit({ secret: true });
export type CredentialSummary = z.infer<typeof CredentialSummarySchema>;

/**
 * Input for creating a new credential (no id - generated by storage).
 */
export type CredentialInput = Omit<Credential, "id" | "metadata">;

/** Result of saving a new credential */
export type SaveResult = { id: string; metadata: Metadata };

// Storage adapter interface - multi-tenant with userId scoping
export interface StorageAdapter {
  /** Create a new credential, returns ID and metadata */
  save(credential: CredentialInput, userId: string): Promise<SaveResult>;
  /** Update an existing credential by ID, returns updated metadata */
  update(id: string, credential: CredentialInput, userId: string): Promise<Metadata>;
  get(id: string, userId: string): Promise<Credential | null>;
  list(type: string, userId: string): Promise<CredentialSummary[]>;
  delete(id: string, userId: string): Promise<void>;
}

/**
 * Request body for PUT /v1/credentials/:type
 * Service generates id, type comes from URL, metadata is auto-generated
 */
export const CredentialCreateRequestSchema = z.object({
  provider: z.string().min(1),
  label: z.string().min(1),
  secret: z.record(z.string(), z.unknown()),
});

/**
 * Client registration details for OAuth provider.
 * Stored on pending flow to ensure callback uses same config that built auth URL.
 */
export type ClientRegistration = {
  client_id: string;
  client_secret?: string;
  redirect_uris: string[];
  scope?: string;
  token_endpoint_auth_method?: string;
};
