FROM joseluisq/static-web-server:2.40.1

COPY apps/static/robots-auth-hellofriday.txt /var/www/robots/robots-auth-hellofriday.txt
COPY apps/static/robots-otel-hellofriday.txt /var/www/robots/robots-otel-hellofriday.txt
COPY apps/static/robots-share-hellofriday.txt /var/www/robots/robots-share-hellofriday.txt
COPY apps/static/robots-signal-hellofriday.txt /var/www/robots/robots-signal-hellofriday.txt
COPY apps/static/robots-static-hellofriday.txt /var/www/robots/robots-static-hellofriday.txt

COPY apps/static/logo-mark.png /var/www/logo/logo-mark.png
COPY apps/static/logo.png /var/www/logo/logo.png
