/**
 * CSV Operations Tool
 *
 * Performs operations on CSV files using LLM-guided data manipulation.
 * The tool parses CSV files and uses an LLM with specialized tools to execute
 * operations like filtering, sorting, joining, and aggregating data.
 *
 */

import Papa from "npm:papaparse@5.4.1";
import { client, parseResult } from "@atlas/client/v2";
import { anthropic } from "@atlas/core";
import { getTodaysDate, stringifyError } from "@atlas/utils";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { generateText } from "ai";
import { z } from "zod";
import type { ToolContext } from "../../types.ts";
import { createErrorResponse, createSuccessResponse } from "../../utils.ts";
import type { OperationResult, ParsedCsvFilesMap } from "./operations.ts";
import { getOperationTools } from "./operations.ts";
import type { CsvCell, ParsedCsvFile } from "./schemas.ts";

/**
 * Input schema for CSV operations tool
 */
const CsvOperationInputSchema = z.object({
  csvFiles: z
    .array(z.string())
    .min(1)
    .describe("Array of absolute file paths to CSV files to process"),
  task: z
    .string()
    .min(1)
    .describe(
      "Description of the operation to perform (e.g., 'filter rows where sales > 1000', 'sort by date descending', 'join on customer_id')",
    ),
  workspaceId: z.string().min(1).describe("Workspace ID where the result artifact will be saved"),
});

/**
 * Parse a single CSV file and return structured data
 */
async function parseCsvFile(filePath: string): Promise<ParsedCsvFile> {
  const content = await Deno.readTextFile(filePath);

  const parsed = Papa.parse<Record<string, CsvCell>>(content, {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: "greedy",
    transformHeader: (header: string) => header.trim(),
    beforeFirstChunk: (chunk: string) => {
      const lines = chunk.split("\n");

      // Find the first line that looks like a valid header:
      // - Has multiple non-empty values
      // - Doesn't have auto-generated column names pattern
      for (let i = 0; i < Math.min(lines.length, 10); i++) {
        const line = lines[i]?.trim();
        if (!line) continue;

        const values = line.split(",").map((v) => v.trim().replace(/^"|"$/g, ""));
        const nonEmptyCount = values.filter((v) => v !== "").length;
        const hasAutoGeneratedNames = values.some((v) => /^_\d+$/.test(v));

        // Valid header: mostly populated, no auto-generated names
        if (nonEmptyCount >= values.length / 2 && !hasAutoGeneratedNames) {
          // Return CSV starting from this line
          return lines.slice(i).join("\n");
        }
      }

      // No valid header found, return original
      return chunk;
    },
  });

  if (!parsed.meta.fields || parsed.meta.fields.length === 0) {
    throw new Error(`CSV file ${filePath} has no header row or columns`);
  }

  // Filter out rows where all values are null/empty
  const data = parsed.data.filter((row: Record<string, CsvCell>) => {
    const values = Object.values(row);
    return values.some((v) => v !== null && v !== "" && v !== undefined);
  });

  const columns = parsed.meta.fields as string[];
  const fileName = filePath.split("/").pop() || filePath;

  return { filePath, fileName, data, rowCount: data.length, columns };
}

/**
 * Build system prompt for CSV operations
 * Only includes metadata - actual data access happens through tools
 */
function buildSystemPrompt(parsedFiles: ParsedCsvFile[]): string {
  const fileDescriptions = parsedFiles
    .map((file) => {
      return `
File: ${file.fileName}
- Path: ${file.filePath}
- Rows: ${file.rowCount}
- Columns: ${file.columns.join(", ")}
`;
    })
    .join("\n");

  return `You orchestrate CSV data operations using tools.

Available files:
${fileDescriptions}

IMPORTANT - State Mutation Model:
- Operations modify files IN-PLACE. After filtering sales.csv, sales.csv contains ONLY filtered rows.
- Joins overwrite fileName1 with the join result. After csv_join(sales.csv, products.csv), sales.csv becomes the joined data. products.csv remains unchanged.
- Subsequent operations on a file operate on its CURRENT STATE (after transformations), not the original data.
- To chain operations: operate on the same file sequentially (e.g., filter sales.csv, then sort sales.csv).
- Column names may change after joins (colliding columns get prefixed).

Tools return metadata only (row counts, success messages) - not actual data. Use csv_get_rows to inspect data structure when needed.

For read-only requests ("read", "describe", "preview"), use csv_get_rows to sample data, then describe what you see. Don't transform.

For transformation requests, chain tools as needed (filter, sort, join, aggregate).

Provide a concise summary:
1. What you did (1-2 sentences)
2. For each file: name, row count, column count, brief description of columns
3. For read-only: note that artifacts contain unchanged data

Current datetime (UTC): ${getTodaysDate()}`;
}

/**
 * Execute CSV operations using LLM with tool access
 * The LLM receives only metadata and uses tools to manipulate the actual data
 */
async function executeCsvOperation(
  parsedFiles: ParsedCsvFile[],
  task: string,
  context: ToolContext,
): Promise<{ summary: string; result: OperationResult }> {
  const systemPrompt = buildSystemPrompt(parsedFiles);

  context.logger.info("Starting CSV operation", {
    fileCount: parsedFiles.length,
    totalRows: parsedFiles.reduce((sum, f) => sum + f.rowCount, 0),
    task,
  });

  // Track the final result of operations
  const operationResult: OperationResult = { dataByFile: {}, operations: [] };

  // Create tools that close over a file map and operationResult
  const fileMap: ParsedCsvFilesMap = Object.fromEntries(
    parsedFiles.map((f) => [f.fileName, f] as const),
  );

  // Initialize per-file data maps with original data
  for (const f of parsedFiles) {
    operationResult.dataByFile[f.fileName] = f.data;
  }

  const tools = getOperationTools(fileMap, operationResult);

  const result = await generateText({
    model: anthropic("claude-sonnet-4-20250514"),
    system: systemPrompt,
    prompt: task,
    tools,
    maxRetries: 3,
  });

  context.logger.info("CSV operation completed", {
    responseLength: result.text.length,
    operationsPerformed: operationResult.operations.length,
  });

  return { summary: result.text, result: operationResult };
}

/**
 * Register the CSV analysis tool with the MCP server
 */
export function registerCsvTool(server: McpServer, context: ToolContext): void {
  server.registerTool(
    "csv",
    {
      description:
        "Use this tool to read CSV file data and perform operations such as filtering, sorting, joining, and aggregating. The result will be saved as an artifact.",
      inputSchema: {
        csvFiles: z.array(z.string()).describe("Absolute paths to CSV files"),
        task: z
          .string()
          .describe("Plain-language instruction for the operation (e.g. 'filter where x > 10')"),
        workspaceId: z.string().describe("Workspace ID to save the result as a table artifact"),
      },
    },
    async (params) => {
      try {
        // Validate input without throwing
        const inputResult = CsvOperationInputSchema.safeParse(params);
        if (!inputResult.success) {
          context.logger.error("Invalid CSV tool parameters", { issues: inputResult.error.issues });
          return createErrorResponse(
            "Invalid parameters for CSV tool",
            inputResult.error.issues.map((i) => ({ path: i.path, message: i.message })),
          );
        }
        const input = inputResult.data;

        // Parse all CSV files
        context.logger.info("Parsing CSV files", { fileCount: input.csvFiles.length });
        const parsedFiles: ParsedCsvFile[] = [];
        const failedParses: Array<{ filePath: string; error: string }> = [];

        for (const filePath of input.csvFiles) {
          try {
            const parsed = await parseCsvFile(filePath);
            parsedFiles.push(parsed);
            context.logger.debug("Parsed CSV file", {
              filePath,
              rowCount: parsed.rowCount,
              columnCount: parsed.columns.length,
            });
          } catch (error) {
            const errorText = stringifyError(error);
            context.logger.error("Failed to parse CSV file", { filePath, error: errorText });
            failedParses.push({ filePath, error: errorText });
            // Continue parsing remaining files instead of throwing
          }
        }

        if (parsedFiles.length === 0) {
          return createErrorResponse("No CSV files were successfully parsed", { failedParses });
        }

        // Check for file name collisions
        const fileNames = parsedFiles.map((f) => f.fileName);
        const uniqueNames = new Set(fileNames);
        if (fileNames.length !== uniqueNames.size) {
          const duplicates = fileNames.filter((name, index) => fileNames.indexOf(name) !== index);
          return createErrorResponse(
            `Duplicate file names detected: ${duplicates.join(", ")}. Files must have unique names.`,
          );
        }

        // Execute operation with LLM
        const { summary, result } = await executeCsvOperation(parsedFiles, input.task, context);

        try {
          const artifactIds: string[] = [];
          const nameToIdPairs: string[] = [];

          // Save all input files as artifacts
          for (const f of parsedFiles) {
            const rows = result.dataByFile[f.fileName] ?? f.data;
            const columns = rows.length > 0 && rows[0] ? Object.keys(rows[0]) : f.columns;
            const tableData = { columns, rows };
            const response = await parseResult(
              client.artifactsStorage.index.$post({
                json: {
                  type: "table",
                  data: { type: "table", version: 1, data: tableData },
                  summary: `Content of csv file ${f.fileName}`,
                  workspaceId: input.workspaceId,
                },
              }),
            );
            if (!response.ok) {
              const err = stringifyError(response.error);
              context.logger.error("Failed to save table artifact", {
                error: err,
                file: f.fileName,
              });
              return createErrorResponse("Failed to save result artifact", err);
            }
            const id = response.data.artifact.id;
            artifactIds.push(id);
            nameToIdPairs.push(`- ${f.fileName} -> ${id}`);
          }

          // Build final summary with mapping
          const mappingText = nameToIdPairs.join("\n");
          const combinedSummary = `${summary}\n\ncsv_name->artifactId:\n${mappingText}`;

          return createSuccessResponse({ summary: combinedSummary, artifactIds });
        } catch (error) {
          const err = stringifyError(error);
          context.logger.error("Exception while saving table artifact", { error: err });
          return createErrorResponse("Failed to save result artifact", err);
        }
      } catch (error) {
        context.logger.error("CSV operation failed", { error: error });
        return createErrorResponse("CSV operation failed", stringifyError(error));
      }
    },
  );

  context.logger.info("Registered csv tool");
}
