/**
 * CSV Parsing and Prompt Utilities
 */

import Papa from "npm:papaparse@5.4.1";
import { anthropic } from "@atlas/core";
import { generateText } from "ai";
import { getTodaysDate, stringifyError } from "@atlas/utils";
import { basename } from "jsr:@std/path@1";
import type { ToolContext } from "../../types.ts";
import type { OperationResult, ParsedCsvFilesMap } from "./operations.ts";
import { getOperationTools } from "./operations.ts";
import type { CsvCell, ParsedCsvFile } from "./schemas.ts";

/**
 * Maximum allowed CSV file size in MB
 */
const MAX_CSV_SIZE_MB = 100;

/**
 * Maximum number of lines to scan when searching for CSV header
 */
const MAX_HEADER_SCAN_LINES = 10;

/**
 * Find the first valid header line in CSV content, skipping garbage lines
 *
 * Valid header criteria:
 * - At least half of the fields are non-empty
 * - No auto-generated column names (like _1, _2, etc.)
 *
 * @param content - Raw CSV file content
 * @returns CSV content starting from the valid header line
 */
export function findHeaderLine(content: string): string {
  const lines = content.split("\n");

  // Scan first N lines for valid header
  for (let i = 0; i < Math.min(lines.length, MAX_HEADER_SCAN_LINES); i++) {
    const line = lines[i]?.trim();
    if (!line) continue;

    const values = line.split(",").map((v) => v.trim().replace(/^"|"$/g, ""));
    const nonEmptyCount = values.filter((v) => v !== "").length;
    const hasAutoGeneratedNames = values.some((v) => /^_\d+$/.test(v));

    // Valid header: mostly populated, no auto-generated names
    if (nonEmptyCount >= values.length / 2 && !hasAutoGeneratedNames) {
      return lines.slice(i).join("\n");
    }
  }

  // No valid header found in first N lines, return original content
  return content;
}

/**
 * Parse a single CSV file and return structured data
 *
 * @param filePath - Absolute path to CSV file
 * @returns Parsed CSV data with metadata
 * @throws Error if file exceeds size limit or has invalid format
 */
export async function parseCsvFile(filePath: string): Promise<ParsedCsvFile> {
  // Check file size before reading
  const fileInfo = await Deno.stat(filePath);
  const sizeMB = fileInfo.size / (1024 * 1024);

  if (sizeMB > MAX_CSV_SIZE_MB) {
    throw new Error(
      `CSV file ${filePath} is ${sizeMB.toFixed(1)}MB, exceeds limit of ${MAX_CSV_SIZE_MB}MB`,
    );
  }

  const rawContent = await Deno.readTextFile(filePath);
  const content = findHeaderLine(rawContent);

  const parsed = Papa.parse<Record<string, CsvCell>>(content, {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: "greedy",
    transformHeader: (header: string) => header.trim(),
  });

  if (!parsed.meta.fields || parsed.meta.fields.length === 0) {
    throw new Error(`CSV file ${filePath} has no header row or columns`);
  }

  // Filter out rows where all values are null/empty
  const data = parsed.data.filter((row: Record<string, CsvCell>) => {
    const values = Object.values(row);
    return values.some((v) => v !== null && v !== "" && v !== undefined);
  });

  const columns = parsed.meta.fields as string[];
  const fileName = basename(filePath);

  return { filePath, fileName, data, rowCount: data.length, columns };
}

/**
 * Parse multiple CSV files with error collection
 *
 * @param filePaths - Array of absolute file paths
 * @returns Parsed files and parsing failures
 */
export async function parseCsvFiles(
  filePaths: string[],
): Promise<{ parsed: ParsedCsvFile[]; failed: Array<{ filePath: string; error: string }> }> {
  const parsed: ParsedCsvFile[] = [];
  const failed: Array<{ filePath: string; error: string }> = [];

  for (const filePath of filePaths) {
    try {
      const result = await parseCsvFile(filePath);
      parsed.push(result);
    } catch (error) {
      failed.push({ filePath, error: stringifyError(error) });
    }
  }

  return { parsed, failed };
}

/**
 * Build system prompt for CSV operations
 * Only includes metadata - actual data access happens through tools
 */
export function buildSystemPrompt(parsedFiles: ParsedCsvFile[]): string {
  const fileDescriptions = parsedFiles
    .map((file) => {
      return `
File: ${file.fileName}
- Path: ${file.filePath}
- Rows: ${file.rowCount}
- Columns: ${file.columns.join(", ")}
`;
    })
    .join("\n");

  return `You orchestrate CSV data operations using tools.

Available files:
${fileDescriptions}

IMPORTANT - State Mutation Model:
- Operations modify files IN-PLACE. After filtering sales.csv, sales.csv contains ONLY filtered rows.
- Joins overwrite fileName1 with the join result. After csv_join(sales.csv, products.csv), sales.csv becomes the joined data. products.csv remains unchanged.
- Subsequent operations on a file operate on its CURRENT STATE (after transformations), not the original data.
- To chain operations: operate on the same file sequentially (e.g., filter sales.csv, then sort sales.csv).
- Column names may change after joins (colliding columns get prefixed).

Tools return metadata only (row counts, success messages) - not actual data. Use csv_get_rows to inspect data structure when needed.

For read-only requests ("read", "describe", "preview"), use csv_get_rows to sample data, then describe what you see. Don't transform.

For transformation requests, chain tools as needed (filter, sort, join, aggregate).

Provide a concise summary:
1. What you did (1-2 sentences)
2. For each file: name, row count, column count, brief description of columns
3. For read-only: note that artifacts contain unchanged data

Current datetime (UTC): ${getTodaysDate()}`;
}

/**
 * Execute CSV operations using LLM with tool access
 * The LLM receives only metadata and uses tools to manipulate the actual data
 */
export async function executeCsvOperation(
  parsedFiles: ParsedCsvFile[],
  task: string,
  context: ToolContext,
): Promise<{ summary: string; result: OperationResult }> {
  const systemPrompt = buildSystemPrompt(parsedFiles);

  context.logger.info("Starting CSV operation", {
    fileCount: parsedFiles.length,
    totalRows: parsedFiles.reduce((sum, f) => sum + f.rowCount, 0),
    task,
  });

  // Track the final result of operations
  const operationResult: OperationResult = { dataByFile: {}, columnsByFile: {}, operations: [] };

  // Create tools that close over a file map and operationResult
  const fileMap: ParsedCsvFilesMap = Object.fromEntries(
    parsedFiles.map((f) => [f.fileName, f] as const),
  );

  // Initialize per-file data and column maps with original data
  for (const f of parsedFiles) {
    operationResult.dataByFile[f.fileName] = f.data;
    operationResult.columnsByFile[f.fileName] = f.columns;
  }

  const tools = getOperationTools(fileMap, operationResult);

  const result = await generateText({
    model: anthropic("claude-sonnet-4-20250514"),
    system: systemPrompt,
    prompt: task,
    tools,
    maxRetries: 3,
  });

  context.logger.info("CSV operation completed", {
    responseLength: result.text.length,
    operationsPerformed: operationResult.operations.length,
  });

  return { summary: result.text, result: operationResult };
}
