import type { UserIdentity } from "@atlas/atlasd";
import { resolve } from "$app/paths";
import { uploadArtifact, validateFile } from "$lib/utils/upload";
import { getContext, setContext } from "svelte";
import { SvelteMap } from "svelte/reactivity";

const KEY = Symbol();

/**
 * Represents a file staged for upload in the chat input.
 * Status tracks the upload lifecycle from initiation to completion.
 */
export interface StagedFile {
  /** Unique key - generated by add() */
  id: string;
  /** Populated after successful upload */
  artifactId?: string;
  /** Original filename */
  name: string;
  /** File size in bytes for display */
  size: number;
  /** Bytes uploaded so far (for progress display) */
  loaded: number;
  /** Upload lifecycle status */
  status: "uploading" | "converting" | "ready" | "error";
  /** Error message if status === "error" */
  error?: string;
  /** AbortController for cancelling in-flight uploads */
  abortController?: AbortController;
}

export function isFileInProgress(file: StagedFile): boolean {
  return file.status === "uploading" || file.status === "converting";
}

export type KeyboardModifier = "shift" | "option" | "command" | "control";
type KeyboardValue = { key: string | null; modifiers: KeyboardModifier[]; pressing?: boolean };

function createKeyboard() {
  let state = $state<KeyboardValue | undefined>();
  return {
    get state() {
      return state;
    },
    update: (value: KeyboardValue | undefined) => {
      state = value;
    },
  };
}

function createStagedFiles() {
  const state = new SvelteMap<string, StagedFile>();

  return {
    get state() {
      return state;
    },

    /** Add a new staged file. Returns the generated ID. */
    add: (file: Omit<StagedFile, "id">): string => {
      const id = crypto.randomUUID();
      state.set(id, { id, ...file });
      return id;
    },

    /** Update an existing staged file by ID. */
    update: (
      id: string,
      updates: Partial<Pick<StagedFile, "artifactId" | "status" | "error" | "loaded">>,
    ) => {
      const existing = state.get(id);
      if (existing) {
        state.set(id, { ...existing, ...updates });
      }
    },

    /** Remove a staged file by ID. */
    remove: (id: string) => {
      state.delete(id);
    },

    /** Cancel an in-flight upload and remove it from staged files. */
    cancel: (id: string) => {
      const existing = state.get(id);
      if (existing?.abortController) {
        existing.abortController.abort();
      }
      state.delete(id);
    },

    /** Clear all staged files. Called after successful message send. */
    clear: () => {
      state.clear();
    },
  };
}

function getRouteConfig() {
  return {
    main: "/",
    library: {
      list: resolve("/library", {}),
      item: (libraryId: string) => resolve("/library/[libraryId]", { libraryId }),
    },
    sessions: {
      list: resolve("/sessions", {}),
      item: (sessionId: string) => resolve("/sessions/[sessionId]", { sessionId }),
    },
    skills: {
      list: resolve("/skills", {}),
      item: (skillId: string, namespace?: string, name?: string) =>
        namespace && name
          ? resolve("/skills/[skillId]/[[namespace]]/[[name]]", { skillId, namespace, name })
          : resolve("/skills/[skillId]", { skillId }),
    },
    chat: { item: (chatId: string) => resolve("/chat/[chatId]", { chatId }) },
    spaces: {
      item: (spaceId: string, view?: string) =>
        view
          ? resolve("/spaces/[spaceId]/[view]", { spaceId, view })
          : resolve("/spaces/[spaceId]", { spaceId }),
    },
    settings: resolve("/settings", {}),
  } as const;
}

class AppContext {
  keyboard = createKeyboard();
  routes = getRouteConfig();
  stagedFiles = createStagedFiles();

  addWorkspaceDialogOpen = $state(false);
  user = $state<UserIdentity | null>(null);

  usage = $derived.by(() => {
    const raw = this.user?.usage ?? 0;
    return {
      fraction: raw,
      percent: Math.round(raw * 100),
      remaining: Math.round((1 - raw) * 100),
      showSidebarWarning: raw >= 0.5,
      showInputWarning: raw >= 0.75,
    };
  });
}

export function setAppContext() {
  const ctx = new AppContext();

  return setContext(KEY, ctx);
}

export function getAppContext() {
  return getContext<ReturnType<typeof setAppContext>>(KEY);
}

/**
 * Handles file drop from drag-and-drop or file input.
 * Validates files client-side, adds them to staged files, and kicks off parallel uploads.
 * Returns immediately - does not await upload completion.
 *
 * @param appCtx - The app context containing stagedFiles
 * @param files - Array of File objects from drop event or file input
 * @param chatId - Optional chat ID to associate artifacts with
 */
export function handleFileDrop(appCtx: AppContext, files: File[], chatId?: string): void {
  for (const file of files) {
    const validation = validateFile(file);
    if (!validation.valid) {
      appCtx.stagedFiles.add({
        name: file.name,
        size: file.size,
        loaded: 0,
        status: "error",
        error: validation.error,
      });
      continue;
    }

    const abortController = new AbortController();
    const tempId = appCtx.stagedFiles.add({
      name: file.name,
      size: file.size,
      loaded: 0,
      status: "uploading",
      abortController,
    });

    uploadArtifact(file, {
      chatId,
      onProgress: (loaded) => {
        appCtx.stagedFiles.update(tempId, { loaded });
      },
      onStatusChange: (status) => {
        appCtx.stagedFiles.update(tempId, { status });
      },
      abortSignal: abortController.signal,
    }).then((result) => {
      if ("artifactId" in result) {
        appCtx.stagedFiles.update(tempId, { artifactId: result.artifactId, status: "ready" });
      } else if (result.error !== "Upload cancelled") {
        // Only show error if not cancelled (cancelled uploads are removed by cancel())
        appCtx.stagedFiles.update(tempId, { status: "error", error: result.error });
      }
    });
  }
}
