import {
  ALLOWED_EXTENSIONS,
  ALLOWED_MIME_TYPES,
  MAX_FILE_SIZE,
} from "@atlas/core/artifacts/file-upload";
import { getAtlasDaemonUrl } from "@atlas/oapi-client";
import { getContext, setContext } from "svelte";
import { SvelteMap } from "svelte/reactivity";
import { resolve } from "$app/paths";

const KEY = Symbol();

/**
 * Represents a file staged for upload in the chat input.
 * Status tracks the upload lifecycle from initiation to completion.
 */
export interface StagedFile {
  /** Unique key - generated by add() */
  id: string;
  /** Populated after successful upload */
  artifactId?: string;
  /** Original filename */
  name: string;
  /** File size in bytes for display */
  size: number;
  /** Upload lifecycle status */
  status: "uploading" | "ready" | "error";
  /** Error message if status === "error" */
  error?: string;
}

export type KeyboardModifier = "shift" | "option" | "command" | "control";
type KeyboardValue = { key: string | null; modifiers: KeyboardModifier[]; pressing?: boolean };

function createKeyboard() {
  let state = $state<KeyboardValue | undefined>();
  return {
    get state() {
      return state;
    },
    update: (value: KeyboardValue | undefined) => {
      state = value;
    },
  };
}

function createStagedFiles() {
  const state = new SvelteMap<string, StagedFile>();

  return {
    get state() {
      return state;
    },

    /** Add a new staged file. Returns the generated ID. */
    add: (file: Omit<StagedFile, "id">): string => {
      const id = crypto.randomUUID();
      state.set(id, { id, ...file });
      return id;
    },

    /** Update an existing staged file by ID. */
    update: (id: string, updates: Partial<Pick<StagedFile, "artifactId" | "status" | "error">>) => {
      const existing = state.get(id);
      if (existing) {
        state.set(id, { ...existing, ...updates });
      }
    },

    /** Remove a staged file by ID. */
    remove: (id: string) => {
      state.delete(id);
    },

    /** Clear all staged files. Called after successful message send. */
    clear: () => {
      state.clear();
    },
  };
}

function getRouteConfig() {
  return {
    main: "/",
    library: {
      list: resolve("/library", {}),
      item: (libraryId: string) => resolve("/library/[libraryId]", { libraryId }),
    },
    sessions: {
      list: resolve("/sessions", {}),
      item: (sessionId: string) => resolve("/sessions/[sessionId]", { sessionId }),
    },
    chat: { item: (chatId: string) => resolve("/chat/[chatId]", { chatId }) },
    spaces: {
      item: (spaceId: string, view?: string) =>
        view
          ? resolve("/spaces/[spaceId]/[view]", { spaceId, view })
          : resolve("/spaces/[spaceId]", { spaceId }),
    },
    settings: resolve("/settings", {}),
  } as const;
}

function getInitialSidebarState(): boolean {
  if (typeof window === "undefined") return false;
  const stored = localStorage.getItem("atlas:sidebarExpanded");
  if (stored !== null) {
    const parsed = JSON.parse(stored);
    if (typeof parsed === "boolean") {
      return parsed;
    }
  }
  return false;
}

class AppContext {
  keyboard = createKeyboard();
  routes = getRouteConfig();
  stagedFiles = createStagedFiles();

  #sidebarExpanded = $state(getInitialSidebarState());
  addWorkspaceDialogOpen = $state(false);

  get sidebarExpanded() {
    return this.#sidebarExpanded;
  }

  set sidebarExpanded(value: boolean) {
    this.#sidebarExpanded = value;
    if (typeof window !== "undefined") {
      localStorage.setItem("atlas:sidebarExpanded", JSON.stringify(value));
    }
  }
}

export function setAppContext() {
  const ctx = new AppContext();

  return setContext(KEY, ctx);
}

export function getAppContext() {
  return getContext<ReturnType<typeof setAppContext>>(KEY);
}

// ─────────────────────────────────────────────────────────────────────────────
// File Validation (client-side UX - server still validates)
// Uses shared constants from @atlas/core/artifacts/file-upload
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Validates a file for upload eligibility.
 * Checks size first, then MIME type, then extension fallback.
 * This is UX enhancement only - server must still validate.
 *
 * @param file - The File object to validate
 * @returns Discriminated union: { valid: true } or { valid: false, error: string }
 */
function validateFile(file: File): { valid: true } | { valid: false; error: string } {
  // Size check first (quick, definitive)
  if (file.size > MAX_FILE_SIZE) {
    return { valid: false, error: "File too large. Maximum size is 25MB." };
  }

  // MIME type check (browser-provided, may be empty)
  if (file.type && ALLOWED_MIME_TYPES.has(file.type)) {
    return { valid: true };
  }

  // Extension fallback (handles empty/generic MIME types)
  const ext = file.name.toLowerCase().slice(file.name.lastIndexOf("."));
  if (ALLOWED_EXTENSIONS.has(ext)) {
    return { valid: true };
  }

  return {
    valid: false,
    error: "Unsupported file type. Only CSV, JSON, TXT, and MD files are allowed.",
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// File Upload
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Uploads a file to the server artifact endpoint.
 * Returns a discriminated union - caller uses `'artifactId' in result` to check success.
 *
 * @param file - The File object to upload
 * @param chatId - Optional chat ID to associate the artifact with
 * @returns Success: `{ artifactId: string }` | Failure: `{ error: string }`
 */
async function uploadFile(
  file: File,
  chatId?: string,
): Promise<{ artifactId: string } | { error: string }> {
  const formData = new FormData();
  formData.set("file", file);
  if (chatId) formData.set("chatId", chatId);

  try {
    const response = await fetch(`${getAtlasDaemonUrl()}/api/artifacts/upload`, {
      method: "POST",
      body: formData,
    });

    if (!response.ok) {
      // response.json() can throw if body isn't valid JSON (e.g., 502 from proxy)
      const data = await response.json().catch(() => ({}));
      return { error: data.error || `Upload failed (${response.status})` };
    }

    const { artifact } = await response.json();
    return { artifactId: artifact.id };
  } catch (error) {
    // Network error, timeout, or other fetch failure
    return { error: error instanceof Error ? error.message : "Network error" };
  }
}

/**
 * Handles file drop from drag-and-drop or file input.
 * Validates files client-side, adds them to staged files, and kicks off parallel uploads.
 * Returns immediately - does not await upload completion.
 *
 * @param appCtx - The app context containing stagedFiles
 * @param files - Array of File objects from drop event or file input
 * @param chatId - Optional chat ID to associate artifacts with
 */
export function handleFileDrop(appCtx: AppContext, files: File[], chatId?: string): void {
  for (const file of files) {
    // Client-side validation first
    const validation = validateFile(file);
    if (!validation.valid) {
      appCtx.stagedFiles.add({
        name: file.name,
        size: file.size,
        status: "error",
        error: validation.error,
      });
      continue;
    }

    // Add as uploading
    const tempId = appCtx.stagedFiles.add({
      name: file.name,
      size: file.size,
      status: "uploading",
    });

    // Upload immediately (fire and forget - all uploads run in parallel)
    uploadFile(file, chatId).then((result) => {
      if ("artifactId" in result) {
        appCtx.stagedFiles.update(tempId, { artifactId: result.artifactId, status: "ready" });
      } else {
        appCtx.stagedFiles.update(tempId, { status: "error", error: result.error });
      }
    });
  }
}
