import type { UserIdentity } from "@atlas/atlasd";
import {
  ALLOWED_EXTENSIONS,
  ALLOWED_MIME_TYPES,
  MAX_FILE_SIZE,
} from "@atlas/core/artifacts/file-upload";
import { getAtlasDaemonUrl } from "@atlas/oapi-client";
import { resolve } from "$app/paths";
import { getContext, setContext } from "svelte";
import { SvelteMap } from "svelte/reactivity";

const KEY = Symbol();

/**
 * Represents a file staged for upload in the chat input.
 * Status tracks the upload lifecycle from initiation to completion.
 */
export interface StagedFile {
  /** Unique key - generated by add() */
  id: string;
  /** Populated after successful upload */
  artifactId?: string;
  /** Original filename */
  name: string;
  /** File size in bytes for display */
  size: number;
  /** Bytes uploaded so far (for progress display) */
  loaded: number;
  /** Upload lifecycle status */
  status: "uploading" | "ready" | "error";
  /** Error message if status === "error" */
  error?: string;
  /** AbortController for cancelling in-flight uploads */
  abortController?: AbortController;
}

export type KeyboardModifier = "shift" | "option" | "command" | "control";
type KeyboardValue = { key: string | null; modifiers: KeyboardModifier[]; pressing?: boolean };

function createKeyboard() {
  let state = $state<KeyboardValue | undefined>();
  return {
    get state() {
      return state;
    },
    update: (value: KeyboardValue | undefined) => {
      state = value;
    },
  };
}

function createStagedFiles() {
  const state = new SvelteMap<string, StagedFile>();

  return {
    get state() {
      return state;
    },

    /** Add a new staged file. Returns the generated ID. */
    add: (file: Omit<StagedFile, "id">): string => {
      const id = crypto.randomUUID();
      state.set(id, { id, ...file });
      return id;
    },

    /** Update an existing staged file by ID. */
    update: (
      id: string,
      updates: Partial<Pick<StagedFile, "artifactId" | "status" | "error" | "loaded">>,
    ) => {
      const existing = state.get(id);
      if (existing) {
        state.set(id, { ...existing, ...updates });
      }
    },

    /** Remove a staged file by ID. */
    remove: (id: string) => {
      state.delete(id);
    },

    /** Cancel an in-flight upload and remove it from staged files. */
    cancel: (id: string) => {
      const existing = state.get(id);
      if (existing?.abortController) {
        existing.abortController.abort();
      }
      state.delete(id);
    },

    /** Clear all staged files. Called after successful message send. */
    clear: () => {
      state.clear();
    },
  };
}

function getRouteConfig() {
  return {
    main: "/",
    library: {
      list: resolve("/library", {}),
      item: (libraryId: string) => resolve("/library/[libraryId]", { libraryId }),
    },
    sessions: {
      list: resolve("/sessions", {}),
      item: (sessionId: string) => resolve("/sessions/[sessionId]", { sessionId }),
    },
    chat: { item: (chatId: string) => resolve("/chat/[chatId]", { chatId }) },
    spaces: {
      item: (spaceId: string, view?: string) =>
        view
          ? resolve("/spaces/[spaceId]/[view]", { spaceId, view })
          : resolve("/spaces/[spaceId]", { spaceId }),
    },
    settings: resolve("/settings", {}),
  } as const;
}

class AppContext {
  keyboard = createKeyboard();
  routes = getRouteConfig();
  stagedFiles = createStagedFiles();

  addWorkspaceDialogOpen = $state(false);
  user = $state<UserIdentity | null>(null);
}

export function setAppContext() {
  const ctx = new AppContext();

  return setContext(KEY, ctx);
}

export function getAppContext() {
  return getContext<ReturnType<typeof setAppContext>>(KEY);
}

// ─────────────────────────────────────────────────────────────────────────────
// File Validation (client-side UX - server still validates)
// Uses shared constants from @atlas/core/artifacts/file-upload
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Validates a file for upload eligibility.
 * Checks size first, then MIME type, then extension fallback.
 * This is UX enhancement only - server must still validate.
 *
 * @param file - The File object to validate
 * @returns Discriminated union: { valid: true } or { valid: false, error: string }
 */
function validateFile(file: File): { valid: true } | { valid: false; error: string } {
  // Size check first (quick, definitive)
  if (file.size > MAX_FILE_SIZE) {
    return { valid: false, error: "File too large. Maximum size is 500MB." };
  }

  // MIME type check (browser-provided, may be empty)
  if (file.type && ALLOWED_MIME_TYPES.has(file.type)) {
    return { valid: true };
  }

  // Extension fallback (handles empty/generic MIME types)
  const ext = file.name.toLowerCase().slice(file.name.lastIndexOf("."));
  if (ALLOWED_EXTENSIONS.has(ext)) {
    return { valid: true };
  }

  return {
    valid: false,
    error: "Unsupported file type. Only CSV, JSON, TXT, and MD files are allowed.",
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// File Upload
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Uploads a file to the server artifact endpoint using XHR for progress tracking.
 * Returns a discriminated union - caller uses `'artifactId' in result` to check success.
 *
 * @param file - The File object to upload
 * @param chatId - Optional chat ID to associate the artifact with
 * @param onProgress - Callback invoked with bytes uploaded
 * @param abortSignal - AbortSignal to cancel the upload
 * @returns Success: `{ artifactId: string }` | Failure: `{ error: string }`
 */
async function uploadFile(
  file: File,
  chatId?: string,
  onProgress?: (loaded: number) => void,
  abortSignal?: AbortSignal,
): Promise<{ artifactId: string } | { error: string }> {
  const formData = new FormData();
  formData.set("file", file);
  if (chatId) formData.set("chatId", chatId);

  return new Promise((resolve) => {
    const xhr = new XMLHttpRequest();

    xhr.upload.onprogress = (event) => {
      if (event.lengthComputable && onProgress) {
        onProgress(event.loaded);
      }
    };

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        try {
          const { artifact } = JSON.parse(xhr.responseText);
          resolve({ artifactId: artifact.id });
        } catch {
          resolve({ error: "Invalid response from server" });
        }
      } else {
        try {
          const data = JSON.parse(xhr.responseText);
          resolve({ error: data.error || `Upload failed (${xhr.status})` });
        } catch {
          resolve({ error: `Upload failed (${xhr.status})` });
        }
      }
    };

    xhr.onerror = () => {
      resolve({ error: "Network error" });
    };

    xhr.onabort = () => {
      resolve({ error: "Upload cancelled" });
    };

    // Wire up abort signal
    if (abortSignal) {
      abortSignal.addEventListener("abort", () => xhr.abort());
    }

    xhr.open("POST", `${getAtlasDaemonUrl()}/api/artifacts/upload`);
    xhr.send(formData);
  });
}

/**
 * Handles file drop from drag-and-drop or file input.
 * Validates files client-side, adds them to staged files, and kicks off parallel uploads.
 * Returns immediately - does not await upload completion.
 *
 * @param appCtx - The app context containing stagedFiles
 * @param files - Array of File objects from drop event or file input
 * @param chatId - Optional chat ID to associate artifacts with
 */
export function handleFileDrop(appCtx: AppContext, files: File[], chatId?: string): void {
  for (const file of files) {
    // Client-side validation first
    const validation = validateFile(file);
    if (!validation.valid) {
      appCtx.stagedFiles.add({
        name: file.name,
        size: file.size,
        loaded: 0,
        status: "error",
        error: validation.error,
      });
      continue;
    }

    // Create abort controller for this upload
    const abortController = new AbortController();

    // Add as uploading
    const tempId = appCtx.stagedFiles.add({
      name: file.name,
      size: file.size,
      loaded: 0,
      status: "uploading",
      abortController,
    });

    // Progress callback updates loaded bytes
    const onProgress = (loaded: number) => {
      appCtx.stagedFiles.update(tempId, { loaded });
    };

    // Upload immediately (fire and forget - all uploads run in parallel)
    uploadFile(file, chatId, onProgress, abortController.signal).then((result) => {
      if ("artifactId" in result) {
        appCtx.stagedFiles.update(tempId, { artifactId: result.artifactId, status: "ready" });
      } else if (result.error !== "Upload cancelled") {
        // Only show error if not cancelled (cancelled uploads are removed by cancel())
        appCtx.stagedFiles.update(tempId, { status: "error", error: result.error });
      }
    });
  }
}
