/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping
     * @description Returns a ping.
     */
    get: operations["ping"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Agent Discovery
     * @description Returns a list of agents.
     */
    get: operations["listAgents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agents/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Agent Detail
     * @description Returns details of the specified agent.
     */
    get: operations["getAgent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new run
     * @description Create and start a new run for the specified agent.
     */
    post: operations["createRun"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get run status
     * @description Returns the current status and details of a run.
     */
    get: operations["getRun"];
    put?: never;
    /**
     * Resume a run
     * @description Resume a paused or awaiting run.
     */
    post: operations["resumeRun"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel a run
     * @description Cancel the specified run.
     */
    post: operations["cancelRun"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List run events
     * @description Returns a list of events emitted by the run.
     */
    get: operations["listRunEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Session
     * @description Returns details of the specified session.
     */
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @enum {string} */
      code: "server_error" | "invalid_input" | "not_found";
      message: string;
    };
    /**
     * Format: uuid
     * @description Identifier of a session
     */
    SessionId: string;
    /**
     * Format: uuid
     * @description Identifier of a run
     */
    RunId: string;
    /**
     * @description Status of the run
     * @enum {string}
     */
    RunStatus:
      | "created"
      | "in-progress"
      | "awaiting"
      | "cancelling"
      | "cancelled"
      | "completed"
      | "failed";
    /**
     * @description Mode of the request
     * @enum {string}
     */
    RunMode: "sync" | "async" | "stream";
    /** @description A part of a message, containing a specific `content_type` and either inline `content` or `content_url`. Only one of `content` or `content_url` must be provided. */
    MessagePart: {
      name?: string;
      content_type: string;
      content?: string;
      /**
       * @default plain
       * @enum {string}
       */
      content_encoding: "plain" | "base64";
      /** Format: uri */
      content_url?: string;
    } & (unknown | unknown);
    Message: {
      parts: components["schemas"]["MessagePart"][];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      completed_at?: string;
      /** @description Specifies the sender of the message. Allowed values:
       *     - `"user"` for messages sent by an end-user.
       *     - `"agent` for anonymous agent.
       *     - `"agent/{agent_name}"` for messages sent by an agent, where `{agent_name}` is the identifier of the agent.
       */
      role: string;
    };
    /** @description Payload describing what is awaited from the client to continue the run. */
    AwaitRequest: Record<string, never>;
    /** @description Payload sent by the client to resume an awaiting run. */
    AwaitResume: Record<string, never>;
    RunCreateRequest: {
      agent_name: components["schemas"]["AgentName"];
      session_id?: components["schemas"]["SessionId"];
      session?: components["schemas"]["Session"];
      input: components["schemas"]["Message"][];
      mode?: components["schemas"]["RunMode"];
    };
    RunResumeRequest: {
      run_id: components["schemas"]["RunId"];
      await_resume: components["schemas"]["AwaitResume"];
      mode: components["schemas"]["RunMode"];
    };
    RunEventsListResponse: {
      events: components["schemas"]["Event"][];
    };
    AgentsListResponse: {
      agents: components["schemas"]["Agent"][];
    };
    Run: {
      agent_name: components["schemas"]["AgentName"];
      session_id?: components["schemas"]["SessionId"];
      run_id: components["schemas"]["RunId"];
      status: components["schemas"]["RunStatus"];
      await_request?: components["schemas"]["AwaitRequest"];
      output: components["schemas"]["Message"][];
      error?: components["schemas"]["Error"];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      finished_at?: string;
    };
    Session: {
      id: components["schemas"]["SessionId"];
      history: string[];
      /** Format: uri */
      state?: string;
    };
    MessageCreatedEvent: {
      /** @constant */
      type: "message.created";
      message: components["schemas"]["Message"];
    };
    MessagePartEvent: {
      /** @constant */
      type: "message.part";
      part: components["schemas"]["MessagePart"];
    };
    MessageCompletedEvent: {
      /** @constant */
      type: "message.completed";
      message: components["schemas"]["Message"];
    };
    GenericEvent: {
      /** @constant */
      type: "generic";
      generic: Record<string, never>;
    };
    RunCreatedEvent: {
      /** @constant */
      type: "run.created";
      run: components["schemas"]["Run"];
    };
    RunInProgressEvent: {
      /** @constant */
      type: "run.in-progress";
      run: components["schemas"]["Run"];
    };
    RunAwaitingEvent: {
      /** @constant */
      type: "run.awaiting";
      run: components["schemas"]["Run"];
    };
    RunCompletedEvent: {
      /** @constant */
      type: "run.completed";
      run: components["schemas"]["Run"];
    };
    RunCancelledEvent: {
      /** @constant */
      type: "run.cancelled";
      run: components["schemas"]["Run"];
    };
    RunFailedEvent: {
      /** @constant */
      type: "run.failed";
      run: components["schemas"]["Run"];
    };
    ErrorEvent: {
      /** @constant */
      type: "error";
      error: components["schemas"]["Error"];
    };
    Event:
      | components["schemas"]["MessageCreatedEvent"]
      | components["schemas"]["MessagePartEvent"]
      | components["schemas"]["MessageCompletedEvent"]
      | components["schemas"]["GenericEvent"]
      | components["schemas"]["RunCreatedEvent"]
      | components["schemas"]["RunInProgressEvent"]
      | components["schemas"]["RunAwaitingEvent"]
      | components["schemas"]["RunCompletedEvent"]
      | components["schemas"]["RunFailedEvent"]
      | components["schemas"]["RunCancelledEvent"]
      | components["schemas"]["ErrorEvent"];
    /**
     * @description A unique identifier for the agent following the RFC 1123 DNS label naming convention.
     * @example chat
     */
    AgentName: string;
    Agent: {
      name: components["schemas"]["AgentName"];
      /**
       * @description Human-readable description of the agent.
       * @example Conversational agent with memory, supporting real-time search, Wikipedia lookups, and weather updates through integrated tools
       */
      description: string;
      metadata?: components["schemas"]["Metadata"];
      status?: components["schemas"]["Status"];
    };
    /** @description Real-time dynamic metrics and state provided by the system managing the agent. */
    Status: {
      avg_run_tokens?: number;
      /** Format: float */
      avg_run_time_seconds?: number;
      /** @description Percentage of successful runs (0-100). */
      success_rate?: number;
    };
    /**
     * @description Simple tag or enum for classifying agents.
     * @example Chat
     */
    Tag: string | ("Chat" | "RAG" | "Canvas" | "Code" | "Researcher" | "Orchestrator");
    /** @description Static details about the agent, for discovery, classification, and cataloging. */
    Metadata: {
      /** @description Key-value annotation metadata. */
      annotations?: {
        [key: string]: unknown;
      };
      /**
       * @description Full agent documentation in markdown.
       * @example The agent is a conversational system designed to process user messages, maintain context, and generate...
       */
      documentation?: string;
      /**
       * @description SPDX license ID.
       * @example Apache-2.0
       */
      license?: string;
      /**
       * @description Programming language (per GitHub language support).
       * @example Python
       */
      programming_language?: string;
      /** @description Supported human languages (ISO 639-1 codes). */
      natural_languages?: string[];
      /**
       * @description Agent framework, e.g. BeeAI, crewAI, Autogen, AG2.
       * @example BeeAI
       */
      framework?: string;
      /**
       * @description A structured list describing capabilities supported by the agent. Each capability includes a human-readable name and a brief description. This information might be consumed and interpreted by large language models (LLMs).
       *
       * @example [
       *       {
       *         "name": "Conversational AI",
       *         "description": "Handles multi-turn conversations with memory."
       *       },
       *       {
       *         "name": "Vacation Request",
       *         "description": "Handles submission and tracking of vacation requests."
       *       }
       *     ]
       */
      capabilities?: {
        /**
         * @description Human-readable name of the capability.
         * @example Conversational AI
         */
        name: string;
        /**
         * @description Brief description of what the capability provides or enables.
         * @example Handles multi-turn conversations with memory.
         */
        description: string;
      }[];
      /**
       * @description Domains or functional areas applicable to the agent, such as 'finance', 'healthcare', 'supply-chain', or custom-defined domains relevant to your organization or team.
       *
       * @example [
       *       "finance",
       *       "healthcare",
       *       "supply-chain"
       *     ]
       */
      domains?: string[];
      tags?: components["schemas"]["Tag"][];
      created_at?: components["schemas"]["Timestamp"];
      updated_at?: components["schemas"]["Timestamp"];
      author?: components["schemas"]["Person"];
      contributors?: components["schemas"]["Person"][];
      /** @example [
       *       {
       *         "type": "source-code",
       *         "url": "https://github.com/i-am-bee/beeai-platform.git"
       *       },
       *       {
       *         "type": "homepage",
       *         "url": "https://agentcommunicationprotocol.dev"
       *       }
       *     ] */
      links?: components["schemas"]["Link"][];
      dependencies?: components["schemas"]["AgentDependency"][];
      /** @example [
       *       "llama3.3:70b-instruct-fp16",
       *       "llama3.3"
       *     ] */
      recommended_models?: string[];
    };
    GeneralSchema: components["schemas"]["JsonSchema"] | ("chat" | "text");
    /** @description Any valid JSON Schema object. */
    JsonSchema: Record<string, never>;
    Link: {
      /** @enum {string} */
      type: "source-code" | "container-image" | "homepage" | "documentation";
      /** Format: uri */
      url: string;
    };
    /**
     * Format: date-time
     * @description Timestamp in RFC3339/ISO8601 format.
     */
    Timestamp: string;
    Person: {
      /** @example John Smith */
      name: string;
      /**
       * Format: email
       * @example jsmith@example.com
       */
      email?: string;
      /**
       * Format: uri
       * @example https://example.com
       */
      url?: string;
    };
    /** @description **Experimental:** Represents a dependency required by the agent, specifying external resources or capabilities it relies upon, such as other agents, tools, or AI models.
     */
    AgentDependency: {
      /**
       * @description Type of dependency:
       *     - `agent`: Another agent instance required to fulfill certain functionalities.
       *     - `tool`: External tool or utility needed by the agent.
       *     - `model`: Specific AI model that the agent depends on.
       *
       * @example tool
       * @enum {string}
       */
      type?: "agent" | "tool" | "model";
      /**
       * @description Identifier or name of the dependency, such as an agent name, tool identifier, or model name.
       *
       * @example weather
       */
      name?: string;
    };
  };
  responses: {
    /** @description Error response */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ping successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listAgents: {
    parameters: {
      query?: {
        /** @description Maximum number of agents to return. */
        limit?: number;
        /** @description Number of agents to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of agents */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentsListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The name of the agent to retrieve. */
        name: components["schemas"]["AgentName"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createRun: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunCreateRequest"];
      };
    };
    responses: {
      /** @description Run started (streaming or immediate) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
          "text/event-stream": components["schemas"]["Event"];
        };
      };
      /** @description Run accepted for processing */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID of the run. */
        run_id: components["schemas"]["RunId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Run status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  resumeRun: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunResumeRequest"];
      };
    };
    responses: {
      /** @description Run resumed (streaming or immediate) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
          "text/event-stream": components["schemas"]["Event"];
        };
      };
      /** @description Resume request accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  cancelRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID of the run to cancel. */
        run_id: components["schemas"]["RunId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancel request accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Run"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listRunEvents: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UUID of the run. */
        run_id: components["schemas"]["RunId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of run events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunEventsListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the session to retrieve. */
        name: components["schemas"]["SessionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
}
