import type { MCPServerMetadata } from "./types.ts";

/**
 * Static registry of curated MCP servers
 * Converted from JSON for easier TypeScript imports
 */
export const mcpServersRegistry = {
  servers: [
    {
      id: "github-repos-manager",
      name: "GitHub Integration",
      description:
        "Comprehensive GitHub repository automation and management with 89 tools for complete GitHub workflow integration. Features token-based authentication, direct API integration, and no Docker dependency for lightweight performance.",
      category: "development",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "list_repositories",
          description: "List accessible repositories",
          capabilities: ["repository-management"],
        },
        {
          name: "get_repository_info",
          description: "Get repository information",
          capabilities: ["repository-management"],
        },
        {
          name: "create_issue",
          description: "Create GitHub issues",
          capabilities: ["issue-tracking"],
        },
        {
          name: "list_issues",
          description: "List GitHub issues",
          capabilities: ["issue-tracking"],
        },
        {
          name: "create_pull_request",
          description: "Create pull requests",
          capabilities: ["code-review"],
        },
        {
          name: "get_file_contents",
          description: "Get file contents from repository",
          capabilities: ["file-management"],
        },
      ],
      useCases: [
        "repository management",
        "issue tracking",
        "team collaboration",
        "code analysis",
        "automated workflows",
        "content management",
      ],
      securityRating: "high",
      configTemplate: {
        transport: { type: "stdio", command: "npx", args: ["-y", "github-repos-manager-mcp"] },
        auth: { type: "bearer", token_env: "GITHUB_TOKEN" },
        tools: {
          allow: [
            "list_repositories",
            "get_repository_info",
            "get_file_contents",
            "create_issue",
            "list_issues",
            "set_default_repository",
          ],
        },
        env: { GITHUB_TOKEN: "your-github-pat" },
        client_config: { timeout: "60s" },
      },
      documentation: "https://github.com/some-repo/github-repos-manager-mcp",
      repository: "https://github.com/some-repo/github-repos-manager-mcp",
      package: "github-repos-manager-mcp",
    },
    {
      id: "azure",
      name: "Azure Services",
      description:
        "Official Microsoft Azure MCP Server with comprehensive Azure service integration. Features 30+ Azure services, hierarchical command routing, and integrated Azure CLI/Developer CLI support.",
      category: "cloud",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "subscription",
          description: "Azure subscription operations and management",
          capabilities: ["subscription-management"],
        },
        {
          name: "group",
          description: "Resource group operations and listing",
          capabilities: ["resource-management"],
        },
        {
          name: "keyvault",
          description: "Key Vault secrets, keys, and certificates management",
          capabilities: ["security", "key-management"],
        },
        {
          name: "storage",
          description: "Storage account operations, containers, blobs, and tables",
          capabilities: ["storage-management"],
        },
        {
          name: "sql",
          description: "Azure SQL databases and servers management",
          capabilities: ["database-management"],
        },
        {
          name: "monitor",
          description: "Azure Monitor logs and metrics querying",
          capabilities: ["monitoring", "analytics"],
        },
      ],
      useCases: [
        "cloud infrastructure management",
        "DevOps automation",
        "security management",
        "monitoring setup",
        "compliance reporting",
        "Infrastructure as Code generation",
      ],
      securityRating: "high",
      configTemplate: {
        transport: {
          type: "stdio",
          command: "npx",
          args: ["-y", "@azure/mcp@latest", "server", "start"],
        },
        auth: { type: "service_principal" },
        tools: {
          allow: ["subscription", "group", "keyvault", "storage", "sql", "cosmos", "monitor"],
        },
        env: {
          AZURE_TENANT_ID: "your-tenant-id",
          AZURE_CLIENT_ID: "your-client-id",
          AZURE_CLIENT_SECRET: "your-client-secret",
        },
        client_config: { timeout: "120s" },
      },
      documentation: "https://docs.microsoft.com/azure/mcp",
      repository: "https://github.com/microsoft/azure-mcp",
      package: "@azure/mcp",
    },
    {
      id: "stripe",
      name: "Stripe Payments",
      description:
        "Official Stripe MCP server for comprehensive payment processing, subscription management, and financial operations. Features OAuth authentication, restricted API key support, and extensive tool coverage.",
      category: "finance",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "create_customer",
          description: "Create new customer profiles",
          capabilities: ["customer-management"],
        },
        {
          name: "list_customers",
          description: "Retrieve customer lists with filtering",
          capabilities: ["customer-management"],
        },
        {
          name: "create_invoice",
          description: "Generate new invoices",
          capabilities: ["billing", "invoice-management"],
        },
        {
          name: "list_invoices",
          description: "Retrieve invoice collections",
          capabilities: ["billing", "invoice-management"],
        },
        {
          name: "create_subscription",
          description: "Set up new recurring billing",
          capabilities: ["subscription-management"],
        },
        {
          name: "list_subscriptions",
          description: "Retrieve subscription data",
          capabilities: ["subscription-management"],
        },
      ],
      useCases: [
        "e-commerce automation",
        "subscription management",
        "payment processing",
        "financial reporting",
        "invoice automation",
        "customer lifecycle management",
      ],
      securityRating: "high",
      configTemplate: {
        transport: { type: "stdio", command: "npx", args: ["-y", "@stripe/mcp", "--tools=all"] },
        auth: { type: "api_key", token_env: "STRIPE_SECRET_KEY" },
        tools: {
          allow: [
            "create_customer",
            "list_customers",
            "create_invoice",
            "list_invoices",
            "list_subscriptions",
            "get_stripe_account_info",
          ],
        },
        env: { STRIPE_SECRET_KEY: "your-stripe-secret-key" },
        client_config: { timeout: "60s" },
      },
      documentation: "https://stripe.com/docs/mcp",
      repository: "https://github.com/stripe/mcp",
      package: "@stripe/mcp",
    },
    {
      id: "playwright",
      name: "Playwright Browser Automation",
      description:
        "Browser automation using Playwright for web page interaction, testing, and screenshot capture.",
      category: "testing",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "Playwright_navigate",
          description: "Navigate to web pages",
          capabilities: ["browser-automation"],
        },
        {
          name: "Playwright_click",
          description: "Click on web elements",
          capabilities: ["ui-interaction"],
        },
        {
          name: "Playwright_fill",
          description: "Fill form inputs",
          capabilities: ["form-automation"],
        },
        {
          name: "Playwright_screenshot",
          description: "Capture page screenshots",
          capabilities: ["visual-testing"],
        },
        {
          name: "playwright_get_visible_text",
          description: "Extract visible text content",
          capabilities: ["data-extraction"],
        },
      ],
      useCases: [
        "automated testing",
        "web scraping",
        "UI automation",
        "performance monitoring",
        "screenshot generation",
      ],
      securityRating: "medium",
      configTemplate: {
        transport: {
          type: "stdio",
          command: "npx",
          args: ["-y", "@executeautomation/playwright-mcp-server"],
        },
        tools: { allow: ["navigate", "click", "type", "screenshot", "extract_text"] },
        client_config: { timeout: "120s" },
      },
      documentation: "https://github.com/executeautomation/playwright-mcp-server",
      repository: "https://github.com/executeautomation/playwright-mcp-server",
      package: "@executeautomation/playwright-mcp-server",
    },
    {
      id: "time",
      name: "Time & Timezone",
      description:
        "Time operations for scheduling and coordination workflows. Essential for time-sensitive automation.",
      category: "utility",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "get_current_time",
          description: "Get current time in specified IANA timezone",
          capabilities: ["time-management"],
        },
        {
          name: "convert_time",
          description: "Convert time between timezones with DST support",
          capabilities: ["timezone-conversion"],
        },
      ],
      useCases: [
        "scheduling agents",
        "time-based triggers",
        "global workspace coordination",
        "meeting scheduling across timezones",
      ],
      securityRating: "high",
      configTemplate: {
        transport: { type: "stdio", command: "uvx", args: ["mcp-server-time", "--local-timezone"] },
        tools: { allow: ["convert_time", "get_current_time"] },
      },
      documentation: "https://github.com/some-repo/mcp-server-time",
      repository: "https://github.com/some-repo/mcp-server-time",
      package: "mcp-server-time",
    },
    {
      id: "git",
      name: "Git Operations",
      description:
        "Local Git repository operations for Atlas agents. Enables version control automation within workspace contexts.",
      category: "development",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "git_status",
          description: "Check working directory status",
          capabilities: ["version-control"],
        },
        {
          name: "git_diff",
          description: "Compare commits/branches",
          capabilities: ["version-control"],
        },
        { name: "git_commit", description: "Create commits", capabilities: ["version-control"] },
        { name: "git_log", description: "View commit history", capabilities: ["version-control"] },
        {
          name: "git_create_branch",
          description: "Create new branches",
          capabilities: ["branch-management"],
        },
      ],
      useCases: [
        "automated commits",
        "branch analysis",
        "repository maintenance",
        "version control automation",
      ],
      securityRating: "high",
      configTemplate: {
        transport: {
          type: "stdio",
          command: "uvx",
          args: ["mcp-server-git", "--repository", "/workspace"],
        },
        tools: { allow: ["git_status", "git_diff", "git_commit", "git_log"] },
        client_config: { timeout: "60s" },
      },
      documentation: "https://github.com/some-repo/mcp-server-git",
      repository: "https://github.com/some-repo/mcp-server-git",
      package: "mcp-server-git",
    },
    {
      id: "weather",
      name: "Weather Data Service",
      description:
        "Real-time weather forecasts using AccuWeather API. Provides accurate hourly and daily weather data for any location with flexible unit systems.",
      category: "utility",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "weather-get_hourly",
          description: "Get 12-hour weather forecast",
          capabilities: ["weather-data"],
        },
        {
          name: "weather-get_daily",
          description: "Get daily weather forecast",
          capabilities: ["weather-data"],
        },
      ],
      useCases: [
        "location-based applications",
        "travel planning",
        "weather-dependent automation",
        "agriculture",
        "event planning",
      ],
      securityRating: "medium",
      configTemplate: {
        transport: { type: "stdio", command: "npx", args: ["-y", "@timlukahorstmann/mcp-weather"] },
        auth: { type: "api_key", token_env: "ACCUWEATHER_API_KEY" },
        tools: { allow: ["weather-get_hourly", "weather-get_daily"] },
        env: { ACCUWEATHER_API_KEY: "your-api-key" },
        client_config: { timeout: "30s" },
      },
      documentation: "https://github.com/timlukahorstmann/mcp-weather",
      repository: "https://github.com/timlukahorstmann/mcp-weather",
      package: "@timlukahorstmann/mcp-weather",
    },
    {
      id: "google-genai-toolbox",
      name: "Google GenAI Toolbox",
      description:
        "Open-source database toolbox that acts as a control plane between AI applications and databases. Provides centralized tool management, enhanced performance, and end-to-end observability for GenAI applications.",
      category: "development",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "load_toolset",
          description: "Load tool configuration sets",
          capabilities: ["tool-management"],
        },
        {
          name: "execute_query",
          description: "Execute database queries",
          capabilities: ["database-operations"],
        },
        {
          name: "get_schema",
          description: "Get database schema information",
          capabilities: ["schema-analysis"],
        },
      ],
      useCases: [
        "database integration for AI applications",
        "centralized tool management",
        "data access automation",
        "GenAI application development",
      ],
      securityRating: "medium",
      configTemplate: {
        transport: {
          type: "stdio",
          command: "toolbox",
          args: ["--stdio", "--tools-file", "/path/to/tools.yaml"],
        },
        tools: { allow: ["load_toolset", "execute_query", "get_schema", "reload_tools"] },
        env: { TOOLBOX_CONFIG: "/path/to/tools.yaml" },
        client_config: { timeout: "90s" },
      },
      documentation: "https://github.com/google/genai-toolbox",
      repository: "https://github.com/google/genai-toolbox",
      package: "mcp-toolbox",
    },
    {
      id: "google-analytics",
      name: "Google Analytics 4",
      description:
        "GA4 data access with 200+ dimensions and metrics through natural language queries.",
      category: "analytics",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "runReport",
          description: "Custom analytics reports",
          capabilities: ["analytics", "reporting"],
        },
        { name: "getPageViews", description: "Page view analytics", capabilities: ["analytics"] },
        {
          name: "getActiveUsers",
          description: "User activity tracking",
          capabilities: ["analytics", "user-tracking"],
        },
      ],
      useCases: [
        "website analytics",
        "user behavior analysis",
        "performance tracking",
        "marketing insights",
      ],
      securityRating: "medium",
      configTemplate: {
        transport: { type: "stdio", command: "npx", args: ["-y", "mcp-server-google-analytics"] },
        tools: { allow: ["runReport", "getPageViews", "getActiveUsers"] },
        env: {
          GOOGLE_CLIENT_EMAIL: "service-account@project.iam.gserviceaccount.com",
          GOOGLE_PRIVATE_KEY: "your-private-key",
          GA_PROPERTY_ID: "your-ga4-property-id",
        },
        client_config: { timeout: "90s" },
      },
      documentation: "https://github.com/some-repo/mcp-server-google-analytics",
      repository: "https://github.com/some-repo/mcp-server-google-analytics",
      package: "mcp-server-google-analytics",
    },
    {
      id: "auth0",
      name: "Auth0 Identity Management",
      description:
        "Auth0 tenant management through natural language with secure credential storage and OAuth 2.0 device authorization flow.",
      category: "security",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "get_application",
          description: "Get application information",
          capabilities: ["identity-management"],
        },
        {
          name: "list_applications",
          description: "List all applications",
          capabilities: ["identity-management"],
        },
        {
          name: "list_logs",
          description: "List authentication logs",
          capabilities: ["security-monitoring"],
        },
      ],
      useCases: [
        "identity management",
        "authentication setup",
        "security monitoring",
        "user access control",
      ],
      securityRating: "high",
      configTemplate: {
        transport: {
          type: "stdio",
          command: "npx",
          args: ["-y", "@auth0/auth0-mcp-server", "run"],
        },
        auth: { type: "oauth" },
        tools: {
          allow: ["get_application", "list_applications", "list_logs", "get_tenant_settings"],
        },
        env: { DEBUG: "auth0-mcp" },
        client_config: { timeout: "90s" },
      },
      documentation: "https://auth0.com/docs/mcp",
      repository: "https://github.com/auth0/auth0-mcp-server",
      package: "@auth0/auth0-mcp-server",
    },
    {
      id: "linear",
      name: "Linear Project Management",
      description:
        "Linear project management integration for issue tracking, updates, and team coordination.",
      category: "project-management",
      source: "static",
      transportTypes: ["sse"],
      tools: [
        {
          name: "create_issue",
          description: "Create new issues",
          capabilities: ["project-management"],
        },
        {
          name: "update_issue",
          description: "Update existing issues",
          capabilities: ["project-management"],
        },
        {
          name: "list_issues",
          description: "List project issues",
          capabilities: ["project-management"],
        },
      ],
      useCases: [
        "project tracking",
        "issue management",
        "team collaboration",
        "automated reporting",
      ],
      securityRating: "high",
      configTemplate: {
        transport: { type: "sse", url: "https://mcp.linear.app/sse" },
        auth: { type: "bearer", token_env: "LINEAR_API_KEY" },
        tools: { allow: ["create_issue", "update_issue", "list_issues"] },
        client_config: { timeout: "120s" },
      },
      documentation: "https://linear.app/docs/mcp",
      repository: "https://github.com/linear/linear-mcp",
      package: "linear-mcp",
    },
    {
      id: "trello",
      name: "Trello Board Management",
      description:
        "Trello board management through natural language for kanban-style project management. Features built-in rate limiting, dynamic board selection, and comprehensive error handling.",
      category: "project-management",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "list_boards",
          description: "List all boards",
          capabilities: ["project-management"],
        },
        { name: "get_lists", description: "Get board lists", capabilities: ["project-management"] },
        {
          name: "add_card_to_list",
          description: "Add card to list",
          capabilities: ["task-management"],
        },
      ],
      useCases: [
        "kanban project management",
        "task tracking",
        "team coordination",
        "workflow automation",
      ],
      securityRating: "medium",
      configTemplate: {
        transport: { type: "stdio", command: "pnpx", args: ["@delorenj/mcp-server-trello"] },
        auth: { type: "api_key", token_env: "TRELLO_API_KEY" },
        tools: {
          allow: [
            "list_boards",
            "get_lists",
            "get_cards_by_list_id",
            "add_card_to_list",
            "update_card_details",
          ],
        },
        env: { TRELLO_API_KEY: "your-api-key", TRELLO_TOKEN: "your-token" },
        client_config: { timeout: "60s" },
      },
      documentation: "https://github.com/delorenj/mcp-server-trello",
      repository: "https://github.com/delorenj/mcp-server-trello",
      package: "@delorenj/mcp-server-trello",
    },
    {
      id: "notion",
      name: "Notion Workspace",
      description:
        "Official Notion MCP server for database and page management through natural language. Provides live context from Notion workspace based on user access and permissions.",
      category: "content",
      source: "static",
      transportTypes: ["sse"],
      tools: [
        {
          name: "search",
          description: "Search Notion content",
          capabilities: ["content-management"],
        },
        { name: "fetch", description: "Fetch Notion pages", capabilities: ["content-management"] },
        {
          name: "create-pages",
          description: "Create new pages",
          capabilities: ["content-creation"],
        },
      ],
      useCases: ["knowledge management", "documentation", "project planning", "team collaboration"],
      securityRating: "high",
      configTemplate: {
        transport: { type: "sse", url: "https://mcp.notion.com/sse" },
        auth: { type: "oauth" },
        tools: { allow: ["search", "fetch", "create-pages", "update-page", "get-comments"] },
        client_config: { timeout: "90s" },
      },
      documentation: "https://notion.com/docs/mcp",
      repository: "https://github.com/notion/notion-mcp",
      package: "notion-mcp",
    },
    {
      id: "rss",
      name: "RSS Feed Management",
      description:
        "RSS feed management with OPML support and automatic content aggregation. Features MySQL storage, automatic feed updates, and content filtering capabilities.",
      category: "content",
      source: "static",
      transportTypes: ["stdio"],
      tools: [
        {
          name: "get_content",
          description: "Retrieve RSS articles with optional filtering",
          capabilities: ["content-aggregation"],
        },
        {
          name: "get_sources",
          description: "List all configured RSS feed sources",
          capabilities: ["content-management"],
        },
        {
          name: "set_tag",
          description: "Update article status",
          capabilities: ["content-management"],
        },
      ],
      useCases: [
        "content aggregation",
        "news monitoring",
        "research automation",
        "content curation",
      ],
      securityRating: "medium",
      configTemplate: {
        transport: { type: "stdio", command: "npx", args: ["mcp_rss"] },
        tools: { allow: ["get_content", "get_sources", "set_tag"] },
        env: {
          DB_HOST: "localhost",
          DB_PORT: "3306",
          DB_USERNAME: "root",
          DB_PASSWORD: "your-password",
          DB_DATABASE: "mcp_rss",
          OPML_FILE_PATH: "/path/to/your/feeds.opml",
          RSS_UPDATE_INTERVAL: "60",
        },
        client_config: { timeout: "30s" },
      },
      documentation: "https://github.com/some-repo/mcp_rss",
      repository: "https://github.com/some-repo/mcp_rss",
      package: "mcp_rss",
    },
    {
      id: "posthog",
      name: "PostHog Analytics & Feature Flags",
      description:
        "Analytics, feature flags, and error tracking integration for product development insights.",
      category: "analytics",
      source: "static",
      transportTypes: ["sse"],
      tools: [
        {
          name: "query_events",
          description: "Query analytics events",
          capabilities: ["analytics"],
        },
        {
          name: "create_feature_flag",
          description: "Create feature flags",
          capabilities: ["feature-management"],
        },
        {
          name: "get_insights",
          description: "Get analytics insights",
          capabilities: ["analytics"],
        },
      ],
      useCases: ["product analytics", "feature rollouts", "user behavior analysis", "A/B testing"],
      securityRating: "high",
      configTemplate: {
        transport: { type: "sse", url: "https://mcp.posthog.com/sse" },
        auth: { type: "bearer", token_env: "POSTHOG_API_KEY" },
        tools: { allow: ["query_events", "create_feature_flag", "get_insights"] },
        client_config: { timeout: "90s" },
      },
      documentation: "https://posthog.com/docs/mcp",
      repository: "https://github.com/posthog/posthog-mcp",
      package: "@posthog/posthog-mcp",
    },
    {
      id: "sentry",
      name: "Sentry Error Tracking",
      description: "Error tracking, performance monitoring, and AI-powered root cause analysis.",
      category: "development",
      source: "static",
      transportTypes: ["sse"],
      tools: [
        {
          name: "list_issues",
          description: "List project issues",
          capabilities: ["error-tracking"],
        },
        {
          name: "get_project_info",
          description: "Get project information",
          capabilities: ["project-management"],
        },
        {
          name: "create_release",
          description: "Create new releases",
          capabilities: ["release-management"],
        },
      ],
      useCases: [
        "error monitoring",
        "performance optimization",
        "debugging assistance",
        "release management",
      ],
      securityRating: "high",
      configTemplate: {
        transport: { type: "sse", url: "https://mcp.sentry.dev/mcp" },
        auth: { type: "oauth" },
        tools: { allow: ["list_issues", "get_project_info", "create_release"] },
        client_config: { timeout: "60s" },
      },
      documentation: "https://sentry.io/docs/mcp",
      repository: "https://github.com/sentry/sentry-mcp",
      package: "sentry-mcp",
    },
  ],
  categories: [
    "development",
    "cloud",
    "analytics",
    "automation",
    "communication",
    "testing",
    "security",
    "content",
    "finance",
    "utility",
    "database",
    "project-management",
    "monitoring",
  ],
  metadata: { version: "1.0.0", lastUpdated: "2025-01-27", totalServers: 16 },
} as const;
