// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"
)

const getUserIDByTeam = `-- name: GetUserIDByTeam :one

SELECT user_id FROM public.platform_route
WHERE team_id = $1
`

// Signal Gateway routing queries for Slack
// Read-only access for event routing
// Get user ID by Slack team ID
func (q *Queries) GetUserIDByTeam(ctx context.Context, teamID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByTeam, teamID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
