// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"
)

const getWebhookSecret = `-- name: GetWebhookSecret :one

SELECT signing_secret, user_id FROM public.slack_app_webhook
WHERE app_id = $1
`

type GetWebhookSecretRow struct {
	SigningSecret string
	UserID        string
}

// Signal Gateway routing queries for Slack
// Read-only access for event routing
func (q *Queries) GetWebhookSecret(ctx context.Context, appID string) (GetWebhookSecretRow, error) {
	row := q.db.QueryRow(ctx, getWebhookSecret, appID)
	var i GetWebhookSecretRow
	err := row.Scan(&i.SigningSecret, &i.UserID)
	return i, err
}
