/**
 * Delegation budgets (Phase 8 of melodic-strolling-seal plan).
 *
 * Bounds on `delegate` tool invocations spawned from chat or FSM type:llm
 * actions. Workspace-level defaults; per-job override via JobSpecification
 * (per-field merge — job wins per field over workspace).
 *
 * Lives in its own file to break the workspace.ts ↔ jobs.ts cycle:
 * jobs.ts imports DelegationBudgetSchema for per-job override, and
 * workspace.ts imports it for workspace-level config. Mirrors the
 * permissions.ts pattern from `44f5605`.
 *
 * Runtime enforcement (Phase 8): all five fields below are honored by
 * `packages/core/src/delegate/index.ts`. `max_cost_usd` is reserved —
 * plumbed through but not enforced until cost-tracking infrastructure
 * lands.
 */
import { z } from "zod";

export const DelegationBudgetSchema = z.strictObject({
  /**
   * Max delegation depth. 1 = parent can call delegate, child cannot
   * re-delegate. 2 = child can delegate once. Etc. Default: 1 (today's
   * hard cap, enforced via tool-list omission in the child).
   */
  max_depth: z.number().int().positive().optional(),
  /** Max steps (tool calls + LLM turns) per delegate child invocation. */
  max_steps_per_call: z.number().int().positive().optional(),
  /** Max output tokens generated by a delegate child. */
  max_output_tokens: z.number().int().positive().optional(),
  /** Max cumulative input tokens across all steps of a delegate child. */
  max_input_tokens: z.number().int().positive().optional(),
  /** Wall-clock budget per delegate invocation, in milliseconds. */
  max_wall_time_ms: z.number().int().positive().optional(),
  /**
   * Cost budget in USD per delegate invocation. Reserved — not enforced
   * until cost-tracking infrastructure lands. Set to null today to make
   * the field's presence explicit without committing to the surface.
   */
  max_cost_usd: z.number().nullable().optional(),
});

export type DelegationBudget = z.infer<typeof DelegationBudgetSchema>;
