// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BounceIdentityProvider string

const (
	BounceIdentityProviderGoogle BounceIdentityProvider = "google"
)

func (e *BounceIdentityProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BounceIdentityProvider(s)
	case string:
		*e = BounceIdentityProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for BounceIdentityProvider: %T", src)
	}
	return nil
}

type NullBounceIdentityProvider struct {
	BounceIdentityProvider BounceIdentityProvider `json:"bounceIdentityProvider"`
	Valid                  bool                   `json:"valid"` // Valid is true if BounceIdentityProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBounceIdentityProvider) Scan(value interface{}) error {
	if value == nil {
		ns.BounceIdentityProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BounceIdentityProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBounceIdentityProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BounceIdentityProvider), nil
}

func AllBounceIdentityProviderValues() []BounceIdentityProvider {
	return []BounceIdentityProvider{
		BounceIdentityProviderGoogle,
	}
}

type BounceOtpUse string

const (
	BounceOtpUseMagiclink    BounceOtpUse = "magiclink"
	BounceOtpUseEmailconfirm BounceOtpUse = "emailconfirm"
	BounceOtpUseOauthstate   BounceOtpUse = "oauthstate"
	BounceOtpUseCsrf         BounceOtpUse = "csrf"
)

func (e *BounceOtpUse) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BounceOtpUse(s)
	case string:
		*e = BounceOtpUse(s)
	default:
		return fmt.Errorf("unsupported scan type for BounceOtpUse: %T", src)
	}
	return nil
}

type NullBounceOtpUse struct {
	BounceOtpUse BounceOtpUse `json:"bounceOtpUse"`
	Valid        bool         `json:"valid"` // Valid is true if BounceOtpUse is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBounceOtpUse) Scan(value interface{}) error {
	if value == nil {
		ns.BounceOtpUse, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BounceOtpUse.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBounceOtpUse) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BounceOtpUse), nil
}

func AllBounceOtpUseValues() []BounceOtpUse {
	return []BounceOtpUse{
		BounceOtpUseMagiclink,
		BounceOtpUseEmailconfirm,
		BounceOtpUseOauthstate,
		BounceOtpUseCsrf,
	}
}

type BounceAuthUser struct {
	ID                 string             `db:"id" json:"id"`
	LastSignInAt       pgtype.Timestamptz `db:"last_sign_in_at" json:"lastSignInAt"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	Email              string             `db:"email" json:"email"`
	EmailConfirmed     bool               `db:"email_confirmed" json:"emailConfirmed"`
	EmailConfirmedAt   pgtype.Timestamptz `db:"email_confirmed_at" json:"emailConfirmedAt"`
	ConfirmationToken  pgtype.Text        `db:"confirmation_token" json:"confirmationToken"`
	ConfirmationSentAt pgtype.Timestamptz `db:"confirmation_sent_at" json:"confirmationSentAt"`
}

type BounceIdentity struct {
	ID               string                 `db:"id" json:"id"`
	AuthUserID       pgtype.Text            `db:"auth_user_id" json:"authUserId"`
	Email            string                 `db:"email" json:"email"`
	LastSignInAt     pgtype.Timestamptz     `db:"last_sign_in_at" json:"lastSignInAt"`
	CreatedAt        pgtype.Timestamptz     `db:"created_at" json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz     `db:"updated_at" json:"updatedAt"`
	Provider         BounceIdentityProvider `db:"provider" json:"provider"`
	ProviderID       string                 `db:"provider_id" json:"providerId"`
	ProviderAppData  []byte                 `db:"provider_app_data" json:"providerAppData"`
	ProviderUserData []byte                 `db:"provider_user_data" json:"providerUserData"`
}

type BounceOtp struct {
	ID            string             `db:"id" json:"id"`
	Token         string             `db:"token" json:"token"`
	AuthUserID    pgtype.Text        `db:"auth_user_id" json:"authUserId"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	NotValidAfter pgtype.Timestamptz `db:"not_valid_after" json:"notValidAfter"`
	UsedAt        pgtype.Timestamptz `db:"used_at" json:"usedAt"`
	Use           BounceOtpUse       `db:"use" json:"use"`
}

type User struct {
	ID               string             `db:"id" json:"id"`
	BounceAuthUserID pgtype.Text        `db:"bounce_auth_user_id" json:"bounceAuthUserId"`
	FullName         string             `db:"full_name" json:"fullName"`
	Email            string             `db:"email" json:"email"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	DisplayName      string             `db:"display_name" json:"displayName"`
	ProfilePhoto     string             `db:"profile_photo" json:"profilePhoto"`
	PoolAvailable    bool               `db:"pool_available" json:"poolAvailable"`
	Name             pgtype.Text        `db:"name" json:"name"`
}
