// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authIdentityByProviderEmail = `-- name: AuthIdentityByProviderEmail :one
SELECT id, auth_user_id, email, last_sign_in_at, created_at, updated_at, provider, provider_id, provider_app_data, provider_user_data FROM bounce.identity WHERE provider = $1 AND email = $2
`

type AuthIdentityByProviderEmailParams struct {
	Provider BounceIdentityProvider `db:"provider" json:"provider"`
	Email    string                 `db:"email" json:"email"`
}

// AuthIdentityByProviderEmail
//
//	SELECT id, auth_user_id, email, last_sign_in_at, created_at, updated_at, provider, provider_id, provider_app_data, provider_user_data FROM bounce.identity WHERE provider = $1 AND email = $2
func (q *Queries) AuthIdentityByProviderEmail(ctx context.Context, arg *AuthIdentityByProviderEmailParams) (*BounceIdentity, error) {
	row := q.db.QueryRow(ctx, authIdentityByProviderEmail, arg.Provider, arg.Email)
	var i BounceIdentity
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderAppData,
		&i.ProviderUserData,
	)
	return &i, err
}

const authIdentityByProviderID = `-- name: AuthIdentityByProviderID :one
SELECT id, auth_user_id, email, last_sign_in_at, created_at, updated_at, provider, provider_id, provider_app_data, provider_user_data FROM bounce.identity WHERE provider = $1 AND provider_id = $2
`

type AuthIdentityByProviderIDParams struct {
	Provider   BounceIdentityProvider `db:"provider" json:"provider"`
	ProviderID string                 `db:"provider_id" json:"providerId"`
}

// AuthIdentityByProviderID
//
//	SELECT id, auth_user_id, email, last_sign_in_at, created_at, updated_at, provider, provider_id, provider_app_data, provider_user_data FROM bounce.identity WHERE provider = $1 AND provider_id = $2
func (q *Queries) AuthIdentityByProviderID(ctx context.Context, arg *AuthIdentityByProviderIDParams) (*BounceIdentity, error) {
	row := q.db.QueryRow(ctx, authIdentityByProviderID, arg.Provider, arg.ProviderID)
	var i BounceIdentity
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderAppData,
		&i.ProviderUserData,
	)
	return &i, err
}

const authUserByConfirmationToken = `-- name: AuthUserByConfirmationToken :one
SELECT id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at FROM bounce.auth_user WHERE confirmation_token = $1
`

// AuthUserByConfirmationToken
//
//	SELECT id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at FROM bounce.auth_user WHERE confirmation_token = $1
func (q *Queries) AuthUserByConfirmationToken(ctx context.Context, confirmationToken pgtype.Text) (*BounceAuthUser, error) {
	row := q.db.QueryRow(ctx, authUserByConfirmationToken, confirmationToken)
	var i BounceAuthUser
	err := row.Scan(
		&i.ID,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailConfirmed,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationSentAt,
	)
	return &i, err
}

const authUserByEmail = `-- name: AuthUserByEmail :one
SELECT id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at FROM bounce.auth_user WHERE email = $1
`

// AuthUserByEmail
//
//	SELECT id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at FROM bounce.auth_user WHERE email = $1
func (q *Queries) AuthUserByEmail(ctx context.Context, email string) (*BounceAuthUser, error) {
	row := q.db.QueryRow(ctx, authUserByEmail, email)
	var i BounceAuthUser
	err := row.Scan(
		&i.ID,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailConfirmed,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationSentAt,
	)
	return &i, err
}

const authUserByID = `-- name: AuthUserByID :one
SELECT id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at FROM bounce.auth_user WHERE id = $1
`

// AuthUserByID
//
//	SELECT id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at FROM bounce.auth_user WHERE id = $1
func (q *Queries) AuthUserByID(ctx context.Context, id string) (*BounceAuthUser, error) {
	row := q.db.QueryRow(ctx, authUserByID, id)
	var i BounceAuthUser
	err := row.Scan(
		&i.ID,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailConfirmed,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationSentAt,
	)
	return &i, err
}

const claimPoolUser = `-- name: ClaimPoolUser :one
UPDATE public."user"
SET email = $1,
    full_name = $2,
    bounce_auth_user_id = $3,
    display_name = $4,
    profile_photo = $5,
    pool_available = false
WHERE id = (
    SELECT id FROM public."user"
    WHERE pool_available = true
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name
`

type ClaimPoolUserParams struct {
	Email            string      `db:"email" json:"email"`
	FullName         string      `db:"full_name" json:"fullName"`
	BounceAuthUserID pgtype.Text `db:"bounce_auth_user_id" json:"bounceAuthUserId"`
	DisplayName      string      `db:"display_name" json:"displayName"`
	ProfilePhoto     string      `db:"profile_photo" json:"profilePhoto"`
}

// Claims an available pool user by updating it with real user data.
// Uses FOR UPDATE SKIP LOCKED to prevent race conditions on concurrent signups.
// Returns no rows if pool is empty.
//
//	UPDATE public."user"
//	SET email = $1,
//	    full_name = $2,
//	    bounce_auth_user_id = $3,
//	    display_name = $4,
//	    profile_photo = $5,
//	    pool_available = false
//	WHERE id = (
//	    SELECT id FROM public."user"
//	    WHERE pool_available = true
//	    ORDER BY created_at ASC
//	    LIMIT 1
//	    FOR UPDATE SKIP LOCKED
//	)
//	RETURNING id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name
func (q *Queries) ClaimPoolUser(ctx context.Context, arg *ClaimPoolUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, claimPoolUser,
		arg.Email,
		arg.FullName,
		arg.BounceAuthUserID,
		arg.DisplayName,
		arg.ProfilePhoto,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BounceAuthUserID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.ProfilePhoto,
		&i.PoolAvailable,
		&i.Name,
	)
	return &i, err
}

const confirmAuthUser = `-- name: ConfirmAuthUser :one
UPDATE bounce.auth_user
SET
    email_confirmed = true,
    email_confirmed_at = now(),
    confirmation_token = null,
    confirmation_sent_at = null
WHERE
    email = $1
    AND id = $2
RETURNING id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at
`

type ConfirmAuthUserParams struct {
	Email string `db:"email" json:"email"`
	ID    string `db:"id" json:"id"`
}

// ConfirmAuthUser
//
//	UPDATE bounce.auth_user
//	SET
//	    email_confirmed = true,
//	    email_confirmed_at = now(),
//	    confirmation_token = null,
//	    confirmation_sent_at = null
//	WHERE
//	    email = $1
//	    AND id = $2
//	RETURNING id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at
func (q *Queries) ConfirmAuthUser(ctx context.Context, arg *ConfirmAuthUserParams) (*BounceAuthUser, error) {
	row := q.db.QueryRow(ctx, confirmAuthUser, arg.Email, arg.ID)
	var i BounceAuthUser
	err := row.Scan(
		&i.ID,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailConfirmed,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationSentAt,
	)
	return &i, err
}

const createTempestUser = `-- name: CreateTempestUser :one
INSERT INTO public."user" (bounce_auth_user_id, email, full_name, display_name, profile_photo)
VALUES ($1, $2, $3, $4, $5) RETURNING id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name
`

type CreateTempestUserParams struct {
	BounceAuthUserID pgtype.Text `db:"bounce_auth_user_id" json:"bounceAuthUserId"`
	Email            string      `db:"email" json:"email"`
	FullName         string      `db:"full_name" json:"fullName"`
	DisplayName      string      `db:"display_name" json:"displayName"`
	ProfilePhoto     string      `db:"profile_photo" json:"profilePhoto"`
}

// CreateTempestUser
//
//	INSERT INTO public."user" (bounce_auth_user_id, email, full_name, display_name, profile_photo)
//	VALUES ($1, $2, $3, $4, $5) RETURNING id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name
func (q *Queries) CreateTempestUser(ctx context.Context, arg *CreateTempestUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createTempestUser,
		arg.BounceAuthUserID,
		arg.Email,
		arg.FullName,
		arg.DisplayName,
		arg.ProfilePhoto,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BounceAuthUserID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.ProfilePhoto,
		&i.PoolAvailable,
		&i.Name,
	)
	return &i, err
}

const saveAuthIdentity = `-- name: SaveAuthIdentity :one
INSERT INTO bounce.identity (
    auth_user_id, email, provider, provider_id, provider_app_data, provider_user_data
)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (provider, provider_id, email) DO UPDATE
SET
email = $2,
provider_app_data = $5,
provider_user_data = $6
RETURNING id, auth_user_id, email, last_sign_in_at, created_at, updated_at, provider, provider_id, provider_app_data, provider_user_data
`

type SaveAuthIdentityParams struct {
	AuthUserID       pgtype.Text            `db:"auth_user_id" json:"authUserId"`
	Email            string                 `db:"email" json:"email"`
	Provider         BounceIdentityProvider `db:"provider" json:"provider"`
	ProviderID       string                 `db:"provider_id" json:"providerId"`
	ProviderAppData  []byte                 `db:"provider_app_data" json:"providerAppData"`
	ProviderUserData []byte                 `db:"provider_user_data" json:"providerUserData"`
}

// SaveAuthIdentity
//
//	INSERT INTO bounce.identity (
//	    auth_user_id, email, provider, provider_id, provider_app_data, provider_user_data
//	)
//	VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (provider, provider_id, email) DO UPDATE
//	SET
//	email = $2,
//	provider_app_data = $5,
//	provider_user_data = $6
//	RETURNING id, auth_user_id, email, last_sign_in_at, created_at, updated_at, provider, provider_id, provider_app_data, provider_user_data
func (q *Queries) SaveAuthIdentity(ctx context.Context, arg *SaveAuthIdentityParams) (*BounceIdentity, error) {
	row := q.db.QueryRow(ctx, saveAuthIdentity,
		arg.AuthUserID,
		arg.Email,
		arg.Provider,
		arg.ProviderID,
		arg.ProviderAppData,
		arg.ProviderUserData,
	)
	var i BounceIdentity
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderAppData,
		&i.ProviderUserData,
	)
	return &i, err
}

const saveConfirmedAuthUser = `-- name: SaveConfirmedAuthUser :one
INSERT INTO bounce.auth_user (email, email_confirmed, email_confirmed_at)
VALUES ($1, true, now())
RETURNING id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at
`

// SaveConfirmedAuthUser
//
//	INSERT INTO bounce.auth_user (email, email_confirmed, email_confirmed_at)
//	VALUES ($1, true, now())
//	RETURNING id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at
func (q *Queries) SaveConfirmedAuthUser(ctx context.Context, email string) (*BounceAuthUser, error) {
	row := q.db.QueryRow(ctx, saveConfirmedAuthUser, email)
	var i BounceAuthUser
	err := row.Scan(
		&i.ID,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailConfirmed,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationSentAt,
	)
	return &i, err
}

const saveOTP = `-- name: SaveOTP :one
INSERT INTO bounce.otp (token, auth_user_id, not_valid_after, use, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, auth_user_id, created_at, not_valid_after, used_at, use
`

type SaveOTPParams struct {
	Token         string             `db:"token" json:"token"`
	AuthUserID    pgtype.Text        `db:"auth_user_id" json:"authUserId"`
	NotValidAfter pgtype.Timestamptz `db:"not_valid_after" json:"notValidAfter"`
	Use           BounceOtpUse       `db:"use" json:"use"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

// OTP queries
//
//	INSERT INTO bounce.otp (token, auth_user_id, not_valid_after, use, created_at)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, token, auth_user_id, created_at, not_valid_after, used_at, use
func (q *Queries) SaveOTP(ctx context.Context, arg *SaveOTPParams) (*BounceOtp, error) {
	row := q.db.QueryRow(ctx, saveOTP,
		arg.Token,
		arg.AuthUserID,
		arg.NotValidAfter,
		arg.Use,
		arg.CreatedAt,
	)
	var i BounceOtp
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AuthUserID,
		&i.CreatedAt,
		&i.NotValidAfter,
		&i.UsedAt,
		&i.Use,
	)
	return &i, err
}

const saveTempestUser = `-- name: SaveTempestUser :one
UPDATE public."user"
SET
    full_name = $2,
    display_name = $3,
    profile_photo = $4
WHERE
    id = $1
RETURNING id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name
`

type SaveTempestUserParams struct {
	ID           string `db:"id" json:"id"`
	FullName     string `db:"full_name" json:"fullName"`
	DisplayName  string `db:"display_name" json:"displayName"`
	ProfilePhoto string `db:"profile_photo" json:"profilePhoto"`
}

// SaveTempestUser
//
//	UPDATE public."user"
//	SET
//	    full_name = $2,
//	    display_name = $3,
//	    profile_photo = $4
//	WHERE
//	    id = $1
//	RETURNING id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name
func (q *Queries) SaveTempestUser(ctx context.Context, arg *SaveTempestUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, saveTempestUser,
		arg.ID,
		arg.FullName,
		arg.DisplayName,
		arg.ProfilePhoto,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BounceAuthUserID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.ProfilePhoto,
		&i.PoolAvailable,
		&i.Name,
	)
	return &i, err
}

const saveUnconfirmedAuthUser = `-- name: SaveUnconfirmedAuthUser :one
INSERT INTO bounce.auth_user (email, confirmation_token, confirmation_sent_at)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
SET confirmation_token = $2,
confirmation_sent_at = $3
RETURNING id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at
`

type SaveUnconfirmedAuthUserParams struct {
	Email              string             `db:"email" json:"email"`
	ConfirmationToken  pgtype.Text        `db:"confirmation_token" json:"confirmationToken"`
	ConfirmationSentAt pgtype.Timestamptz `db:"confirmation_sent_at" json:"confirmationSentAt"`
}

// SaveUnconfirmedAuthUser
//
//	INSERT INTO bounce.auth_user (email, confirmation_token, confirmation_sent_at)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (email) DO UPDATE
//	SET confirmation_token = $2,
//	confirmation_sent_at = $3
//	RETURNING id, last_sign_in_at, created_at, updated_at, email, email_confirmed, email_confirmed_at, confirmation_token, confirmation_sent_at
func (q *Queries) SaveUnconfirmedAuthUser(ctx context.Context, arg *SaveUnconfirmedAuthUserParams) (*BounceAuthUser, error) {
	row := q.db.QueryRow(ctx, saveUnconfirmedAuthUser, arg.Email, arg.ConfirmationToken, arg.ConfirmationSentAt)
	var i BounceAuthUser
	err := row.Scan(
		&i.ID,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailConfirmed,
		&i.EmailConfirmedAt,
		&i.ConfirmationToken,
		&i.ConfirmationSentAt,
	)
	return &i, err
}

const setAuthUserLastSignin = `-- name: SetAuthUserLastSignin :exec
UPDATE bounce.auth_user
SET last_sign_in_at = now()
WHERE id = $1
`

// SetAuthUserLastSignin
//
//	UPDATE bounce.auth_user
//	SET last_sign_in_at = now()
//	WHERE id = $1
func (q *Queries) SetAuthUserLastSignin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setAuthUserLastSignin, id)
	return err
}

const setIdentityLastSignin = `-- name: SetIdentityLastSignin :exec
UPDATE bounce.identity
SET last_sign_in_at = now()
WHERE id = $1
`

// SetIdentityLastSignin
//
//	UPDATE bounce.identity
//	SET last_sign_in_at = now()
//	WHERE id = $1
func (q *Queries) SetIdentityLastSignin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setIdentityLastSignin, id)
	return err
}

const tempestUserByAuthUserID = `-- name: TempestUserByAuthUserID :one
SELECT id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name FROM public."user" WHERE bounce_auth_user_id = $1
`

// TempestUserByAuthUserID
//
//	SELECT id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name FROM public."user" WHERE bounce_auth_user_id = $1
func (q *Queries) TempestUserByAuthUserID(ctx context.Context, bounceAuthUserID pgtype.Text) (*User, error) {
	row := q.db.QueryRow(ctx, tempestUserByAuthUserID, bounceAuthUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BounceAuthUserID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.ProfilePhoto,
		&i.PoolAvailable,
		&i.Name,
	)
	return &i, err
}

const tempestUserByID = `-- name: TempestUserByID :one
SELECT id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name FROM public."user" WHERE id = $1
`

// TempestUserByID
//
//	SELECT id, bounce_auth_user_id, full_name, email, created_at, updated_at, display_name, profile_photo, pool_available, name FROM public."user" WHERE id = $1
func (q *Queries) TempestUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, tempestUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BounceAuthUserID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.ProfilePhoto,
		&i.PoolAvailable,
		&i.Name,
	)
	return &i, err
}

const useOTP = `-- name: UseOTP :one
UPDATE bounce.otp
SET used_at = now()
WHERE token = $1
RETURNING id, token, auth_user_id, created_at, not_valid_after, used_at, use
`

// UseOTP
//
//	UPDATE bounce.otp
//	SET used_at = now()
//	WHERE token = $1
//	RETURNING id, token, auth_user_id, created_at, not_valid_after, used_at, use
func (q *Queries) UseOTP(ctx context.Context, token string) (*BounceOtp, error) {
	row := q.db.QueryRow(ctx, useOTP, token)
	var i BounceOtp
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AuthUserID,
		&i.CreatedAt,
		&i.NotValidAfter,
		&i.UsedAt,
		&i.Use,
	)
	return &i, err
}

const validMagicLinkOTPByAuthUserID = `-- name: ValidMagicLinkOTPByAuthUserID :one
SELECT token, created_at, not_valid_after
FROM bounce.otp
WHERE auth_user_id = $1
    AND use = 'magiclink'
    AND used_at IS NULL
    AND not_valid_after > now()
ORDER BY created_at DESC
LIMIT 1
`

type ValidMagicLinkOTPByAuthUserIDRow struct {
	Token         string             `db:"token" json:"token"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	NotValidAfter pgtype.Timestamptz `db:"not_valid_after" json:"notValidAfter"`
}

// ValidMagicLinkOTPByAuthUserID
//
//	SELECT token, created_at, not_valid_after
//	FROM bounce.otp
//	WHERE auth_user_id = $1
//	    AND use = 'magiclink'
//	    AND used_at IS NULL
//	    AND not_valid_after > now()
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) ValidMagicLinkOTPByAuthUserID(ctx context.Context, authUserID pgtype.Text) (*ValidMagicLinkOTPByAuthUserIDRow, error) {
	row := q.db.QueryRow(ctx, validMagicLinkOTPByAuthUserID, authUserID)
	var i ValidMagicLinkOTPByAuthUserIDRow
	err := row.Scan(&i.Token, &i.CreatedAt, &i.NotValidAfter)
	return &i, err
}
