// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPoolUsers = `-- name: CountPoolUsers :one
SELECT COUNT(*)::int FROM public."user" WHERE pool_available = true
`

// CountPoolUsers
//
//	SELECT COUNT(*)::int FROM public."user" WHERE pool_available = true
func (q *Queries) CountPoolUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPoolUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPoolUser = `-- name: CreatePoolUser :one
INSERT INTO public."user" (email, full_name, pool_available)
VALUES (gen_random_uuid()::text || '@pool.internal', '', true)
RETURNING id
`

// CreatePoolUser
//
//	INSERT INTO public."user" (email, full_name, pool_available)
//	VALUES (gen_random_uuid()::text || '@pool.internal', '', true)
//	RETURNING id
func (q *Queries) CreatePoolUser(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, createPoolUser)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    bounce_auth_user_id,
    full_name,
    email,
    created_at,
    updated_at,
    display_name,
    profile_photo
FROM public."user"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID               string             `db:"id" json:"id"`
	BounceAuthUserID pgtype.Text        `db:"bounce_auth_user_id" json:"bounceAuthUserId"`
	FullName         string             `db:"full_name" json:"fullName"`
	Email            string             `db:"email" json:"email"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	DisplayName      string             `db:"display_name" json:"displayName"`
	ProfilePhoto     string             `db:"profile_photo" json:"profilePhoto"`
}

// GetUserByID
//
//	SELECT
//	    id,
//	    bounce_auth_user_id,
//	    full_name,
//	    email,
//	    created_at,
//	    updated_at,
//	    display_name,
//	    profile_photo
//	FROM public."user"
//	WHERE id = $1
func (q *Queries) GetUserByID(ctx context.Context, id string) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.BounceAuthUserID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.ProfilePhoto,
	)
	return &i, err
}

const getUsersAfterCursor = `-- name: GetUsersAfterCursor :many
SELECT
    id,
    bounce_auth_user_id,
    full_name,
    email,
    created_at,
    updated_at,
    display_name,
    profile_photo
FROM public."user"
WHERE id > $1::text
ORDER BY id
LIMIT $2
`

type GetUsersAfterCursorParams struct {
	Column1 string `db:"column_1" json:"column1"`
	Limit   int32  `db:"limit" json:"limit"`
}

type GetUsersAfterCursorRow struct {
	ID               string             `db:"id" json:"id"`
	BounceAuthUserID pgtype.Text        `db:"bounce_auth_user_id" json:"bounceAuthUserId"`
	FullName         string             `db:"full_name" json:"fullName"`
	Email            string             `db:"email" json:"email"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	DisplayName      string             `db:"display_name" json:"displayName"`
	ProfilePhoto     string             `db:"profile_photo" json:"profilePhoto"`
}

// Retrieves users after the given cursor ID.
//
//	SELECT
//	    id,
//	    bounce_auth_user_id,
//	    full_name,
//	    email,
//	    created_at,
//	    updated_at,
//	    display_name,
//	    profile_photo
//	FROM public."user"
//	WHERE id > $1::text
//	ORDER BY id
//	LIMIT $2
func (q *Queries) GetUsersAfterCursor(ctx context.Context, arg *GetUsersAfterCursorParams) ([]*GetUsersAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, getUsersAfterCursor, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersAfterCursorRow{}
	for rows.Next() {
		var i GetUsersAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.BounceAuthUserID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.ProfilePhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersFirstPage = `-- name: GetUsersFirstPage :many
SELECT
    id,
    bounce_auth_user_id,
    full_name,
    email,
    created_at,
    updated_at,
    display_name,
    profile_photo
FROM public."user"
ORDER BY id
LIMIT $1
`

type GetUsersFirstPageRow struct {
	ID               string             `db:"id" json:"id"`
	BounceAuthUserID pgtype.Text        `db:"bounce_auth_user_id" json:"bounceAuthUserId"`
	FullName         string             `db:"full_name" json:"fullName"`
	Email            string             `db:"email" json:"email"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	DisplayName      string             `db:"display_name" json:"displayName"`
	ProfilePhoto     string             `db:"profile_photo" json:"profilePhoto"`
}

// Retrieves the first page of users (no cursor).
//
//	SELECT
//	    id,
//	    bounce_auth_user_id,
//	    full_name,
//	    email,
//	    created_at,
//	    updated_at,
//	    display_name,
//	    profile_photo
//	FROM public."user"
//	ORDER BY id
//	LIMIT $1
func (q *Queries) GetUsersFirstPage(ctx context.Context, limit int32) ([]*GetUsersFirstPageRow, error) {
	rows, err := q.db.Query(ctx, getUsersFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersFirstPageRow{}
	for rows.Next() {
		var i GetUsersFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.BounceAuthUserID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.ProfilePhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasVirtualKey = `-- name: HasVirtualKey :one
SELECT EXISTS(SELECT 1 FROM public.llm_virtualkey WHERE user_id = $1)
`

// HasVirtualKey
//
//	SELECT EXISTS(SELECT 1 FROM public.llm_virtualkey WHERE user_id = $1)
func (q *Queries) HasVirtualKey(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasVirtualKey, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertVirtualKey = `-- name: UpsertVirtualKey :exec
INSERT INTO public.llm_virtualkey (user_id, ciphertext)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET ciphertext = EXCLUDED.ciphertext
`

type UpsertVirtualKeyParams struct {
	UserID     string `db:"user_id" json:"userId"`
	Ciphertext []byte `db:"ciphertext" json:"ciphertext"`
}

// UpsertVirtualKey
//
//	INSERT INTO public.llm_virtualkey (user_id, ciphertext)
//	VALUES ($1, $2)
//	ON CONFLICT (user_id) DO UPDATE SET ciphertext = EXCLUDED.ciphertext
func (q *Queries) UpsertVirtualKey(ctx context.Context, arg *UpsertVirtualKeyParams) error {
	_, err := q.db.Exec(ctx, upsertVirtualKey, arg.UserID, arg.Ciphertext)
	return err
}
