// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObject = `-- name: CreateObject :one

INSERT INTO cortex.object (user_id, content_size, metadata)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateObjectParams struct {
	UserID      string
	ContentSize pgtype.Int8
	Metadata    []byte
}

// Cortex object storage queries
func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createObject, arg.UserID, arg.ContentSize, arg.Metadata)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM cortex.object WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteObject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteObject, id)
	return err
}

const getObjectForUser = `-- name: GetObjectForUser :one
SELECT id, user_id, content_size, metadata, created_at, updated_at, deleted_at
FROM cortex.object
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetObjectForUserParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) GetObjectForUser(ctx context.Context, arg GetObjectForUserParams) (CortexObject, error) {
	row := q.db.QueryRow(ctx, getObjectForUser, arg.ID, arg.UserID)
	var i CortexObject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentSize,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listObjects = `-- name: ListObjects :many
SELECT id, user_id, content_size, metadata, created_at, updated_at, deleted_at
FROM cortex.object
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR metadata->>'workspace_id' = $2)
  AND ($3::text IS NULL OR metadata->>'chat_id' = $3)
ORDER BY created_at DESC
LIMIT $4
OFFSET $5
`

type ListObjectsParams struct {
	UserID      string
	WorkspaceID pgtype.Text
	ChatID      pgtype.Text
	Limit       int32
	Offset      int32
}

func (q *Queries) ListObjects(ctx context.Context, arg ListObjectsParams) ([]CortexObject, error) {
	rows, err := q.db.Query(ctx, listObjects, arg.UserID, arg.WorkspaceID, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CortexObject
	for rows.Next() {
		var i CortexObject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentSize,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentSize = `-- name: UpdateContentSize :exec
UPDATE cortex.object
SET content_size = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateContentSizeParams struct {
	ID          pgtype.UUID
	ContentSize pgtype.Int8
}

func (q *Queries) UpdateContentSize(ctx context.Context, arg UpdateContentSizeParams) error {
	_, err := q.db.Exec(ctx, updateContentSize, arg.ID, arg.ContentSize)
	return err
}

const updateMetadata = `-- name: UpdateMetadata :exec
UPDATE cortex.object
SET metadata = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateMetadataParams struct {
	ID       pgtype.UUID
	Metadata []byte
}

func (q *Queries) UpdateMetadata(ctx context.Context, arg UpdateMetadataParams) error {
	_, err := q.db.Exec(ctx, updateMetadata, arg.ID, arg.Metadata)
	return err
}
