// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package litellmrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKeyUsage = `-- name: GetKeyUsage :one
SELECT COALESCE(spend, 0)::float8 AS spend,
       COALESCE(max_budget, 0)::float8 AS max_budget
FROM "LiteLLM_VerificationToken"
WHERE key_alias = $1
`

type GetKeyUsageRow struct {
	Spend     float64
	MaxBudget float64
}

func (q *Queries) GetKeyUsage(ctx context.Context, keyAlias pgtype.Text) (GetKeyUsageRow, error) {
	row := q.db.QueryRow(ctx, getKeyUsage, keyAlias)
	var i GetKeyUsageRow
	err := row.Scan(&i.Spend, &i.MaxBudget)
	return i, err
}
