#!/bin/bash
# Compile Atlas binary with all required dependencies
# Usage: ./scripts/compile.sh [output-path]

set -e

OUTPUT="${1:-./dist/atlas}"
mkdir -p "$(dirname "$OUTPUT")"

# Get git commit hash for Sentry release tracking
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
echo "Build commit: ${COMMIT_HASH}"

# Embed build commit into the binary by generating build-info.ts
# This file gets compiled into the binary and provides the release version to Sentry
cat > packages/sentry/src/build-info.ts << EOF
// Auto-generated by compile.sh - do not edit manually
export const BUILD_COMMIT = "${COMMIT_HASH}";
EOF

echo "Compiling Atlas to: ${OUTPUT}"

# Enable OTEL at compile time so the binary has telemetry enabled.
# Runtime env vars (OTEL_EXPORTER_OTLP_ENDPOINT, etc) control WHERE data is sent.
# Without this, the compiled binary ignores console.log -> OTEL forwarding.
export OTEL_DENO=true

deno compile \
  --no-check \
  --allow-read \
  --allow-write \
  --allow-net \
  --allow-env \
  --allow-run \
  --allow-sys \
  --allow-ffi \
  --unstable-broadcast-channel \
  --unstable-worker-options \
  --include=apps/atlas-cli \
  --include=examples \
  --include=packages \
  --output "$OUTPUT" \
  ./apps/atlas-cli/src/cli.ts

echo "✅ Compilation complete: ${OUTPUT}"
