#!/usr/bin/env -S deno run --allow-read --allow-write --unstable-kv

// This was generated by claude and is good for spitting out current artifacts in the deno kv
import { getAtlasHome } from "@atlas/utils/paths.server";
import { join } from "@std/path";

const kvPath = join(getAtlasHome(), "storage.db");
const db = await Deno.openKv(kvPath);

console.log("=== Artifacts Database Dump ===\n");

// List all artifacts
const artifactEntries = db.list({ prefix: ["artifact"] });
const latestEntries = db.list({ prefix: ["artifact_latest"] });
const workspaceEntries = db.list({ prefix: ["artifacts_by_workspace"] });
const chatEntries = db.list({ prefix: ["artifacts_by_chat"] });
const deletedEntries = db.list({ prefix: ["artifact_deleted"] });

console.log("--- Artifacts (all revisions) ---");
for await (const entry of artifactEntries) {
  console.log(JSON.stringify({ key: entry.key, value: entry.value }, null, 2));
}

console.log("\n--- Latest Revision Pointers ---");
for await (const entry of latestEntries) {
  console.log(JSON.stringify({ key: entry.key, value: entry.value }, null, 2));
}

console.log("\n--- Workspace Index ---");
for await (const entry of workspaceEntries) {
  console.log(JSON.stringify({ key: entry.key, value: entry.value }, null, 2));
}

console.log("\n--- Chat Index ---");
for await (const entry of chatEntries) {
  console.log(JSON.stringify({ key: entry.key, value: entry.value }, null, 2));
}

console.log("\n--- Deleted Artifacts ---");
for await (const entry of deletedEntries) {
  console.log(JSON.stringify({ key: entry.key, value: entry.value }, null, 2));
}

db.close();
