<script lang="ts">
  import { Chat } from "@ai-sdk/svelte";
  import type { AtlasUIMessage, AtlasUIMessagePart } from "@atlas/agent-sdk";
  import { client, parseResult } from "@atlas/client/v2";
  import type { ArtifactWithContents } from "@atlas/core/artifacts";
  import { GA4, trackApiError, trackEvent, trackNetworkError } from "@atlas/ga4";
  import { getAtlasDaemonUrl } from "@atlas/oapi-client";
  import { createQuery, useQueryClient } from "@tanstack/svelte-query";
  import { afterNavigate, beforeNavigate, goto } from "$app/navigation";
  import { getAppContext, handleFileDrop } from "$lib/app-context.svelte";
  import ChatBufferBlur from "$lib/components/chat-buffer-blur.svelte";
  import { DropdownMenu } from "$lib/components/dropdown-menu";
  import { Icons } from "$lib/components/icons";
  import { IconSmall } from "$lib/components/icons/small";
  import Textarea from "$lib/components/textarea.svelte";
  import DisplayArtifact from "$lib/modules/artifacts/display.svelte";
  import WorkspacePlan from "$lib/modules/artifacts/workspace-plan.svelte";
  import Outline from "$lib/modules/conversation/outline.svelte";
  import ConnectService from "$lib/modules/messages/connect-service.svelte";
  import CredentialLinked from "$lib/modules/messages/credential-linked.svelte";
  import ErrorMessage from "$lib/modules/messages/error-message.svelte";
  import { formatMessage } from "$lib/modules/messages/format";
  import Intent from "$lib/modules/messages/intent.svelte";
  import Progress from "$lib/modules/messages/progress.svelte";
  import Reasoning from "$lib/modules/messages/reasoning.svelte";
  import Request from "$lib/modules/messages/request.svelte";
  import Response from "$lib/modules/messages/response.svelte";
  import ShowDetails from "$lib/modules/messages/show-details.svelte";
  import WorkspaceCreated from "$lib/modules/messages/workspace-created.svelte";
  import { listChats } from "$lib/queries/chats";
  import { formatChatDate, getDatetimeContext } from "$lib/utils/date";
  import { shareChat } from "$lib/utils/share-chat";
  import { DefaultChatTransport } from "ai";
  import { onMount, setContext } from "svelte";
  import { circOut } from "svelte/easing";
  import { SvelteMap } from "svelte/reactivity";
  import { slide } from "svelte/transition";

  /**
   * ChatSession component - handles a single chat instance.
   *
   * This component treats chatId as immutable. When the user navigates to a
   * different chat, the parent destroys this instance and creates a new one
   * via {#key}. This eliminates complex reactive state for ID management.
   */

  interface Props {
    /** Chat ID - always a string, generated by loader for new chats */
    chatId: string;
    /** Whether this is a new (unsaved) chat */
    isNew: boolean;
    /** Chat title (undefined for new chats) */
    title: string | undefined;
    /** Initial messages from loader */
    initialMessages: AtlasUIMessage[];
    /** Pre-fetched artifacts map */
    artifacts: Map<string, ArtifactWithContents>;
  }

  const { chatId, isNew, title, initialMessages, artifacts }: Props = $props();

  /**
   * Formats a file size in bytes to a human-readable string.
   */
  function formatFileSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  // Expose artifacts map to child components via context
  const ARTIFACTS_KEY = Symbol.for("artifacts");
  setContext(ARTIFACTS_KEY, artifacts);

  const appCtx = getAppContext();
  const queryClient = useQueryClient();
  const chatsQuery = createQuery(() => ({
    queryKey: ["recent-chats"],
    queryFn: () => listChats(null),
  }));

  let form = $state<HTMLFormElement | null>(null);
  let message = $state<string>("");
  let textareaAdditionalSize = $state(1);

  // Follow scroll handling
  let scrollContainer = $state<HTMLDivElement | null>(null);
  let showContents = $state(false);
  let showChats = $state(false);

  // Track whether we've already updated the URL for this new chat
  let hasUpdatedUrl = $state(false);

  // AbortController for resumeStream GET requests. The ai-sdk doesn't pass
  // abortSignal to reconnectToStream, so we inject it via our fetch wrapper.
  // This prevents connection leaks when navigating away during stream resume.
  let resumeAbortController: AbortController | null = null;

  // Server-provided turn start timestamp for accurate timer display after refresh
  let turnStartedAt = $state<number | null>(null);

  // Track stream timing for analytics
  let streamStartTime = $state<number | null>(null);
  let previousStatus = $state<string | null>(null);

  const transport = new DefaultChatTransport({
    api: `${getAtlasDaemonUrl()}/api/chat`,
    /**
     * Custom fetch wrapper that:
     * 1. Updates URL when new chat is created (POST succeeds)
     * 2. Injects AbortSignal into GET requests (resumeStream) since ai-sdk
     *    doesn't pass one, causing connection leaks on navigation
     */
    fetch: async (url, init): Promise<Response> => {
      // For GET requests (resumeStream), inject our abort controller's signal
      // since ai-sdk's reconnectToStream doesn't pass abortSignal to fetch
      if (init?.method === "GET" || !init?.method) {
        resumeAbortController = new AbortController();
        init = { ...init, signal: resumeAbortController.signal };
      }

      let response: Response;
      try {
        response = await fetch(url, init);
      } catch (error) {
        // Track network errors (connection failures, timeouts, etc.)
        const message = error instanceof Error ? error.message : "Network error";
        // Don't track aborted requests (user navigated away)
        if (!(error instanceof DOMException && error.name === "AbortError")) {
          trackNetworkError(String(url), message, init?.method ?? "GET");
        }
        throw error;
      }

      // Track API errors (non-2xx responses)
      if (!response.ok) {
        const errorText = await response
          .clone()
          .text()
          .catch(() => "Unknown error");
        trackApiError(String(url), response.status, errorText, init?.method ?? "GET");
      }

      // Capture server-provided turn start time for accurate timer display
      const startedAt = response.headers.get("X-Turn-Started-At");
      if (startedAt) {
        turnStartedAt = parseInt(startedAt, 10);
      }

      // Refresh sidebar on every successful message (chat's updatedAt changes)
      if (init?.method === "POST" && response.ok) {
        queryClient.invalidateQueries({ queryKey: ["chats"], refetchType: "all" });
        // Update URL for new chats (only once)
        if (isNew && !hasUpdatedUrl) {
          hasUpdatedUrl = true;
          window.history.replaceState({}, "", `/chat/${chatId}`);
        }
      }

      return response;
    },
    prepareSendMessagesRequest({ messages, id }) {
      return { body: { message: messages.at(-1), id, datetime: getDatetimeContext() } };
    },
  });

  // Create Chat instance once - no reactive recreation
  // chatId is immutable for this component's lifetime
  const chat = new Chat<AtlasUIMessage>({ id: chatId, messages: initialMessages, transport });

  // Track streaming lifecycle for analytics
  $effect(() => {
    const currentStatus = chat.status;

    // Stream started
    if (
      (currentStatus === "streaming" || currentStatus === "submitted") &&
      previousStatus !== "streaming" &&
      previousStatus !== "submitted"
    ) {
      streamStartTime = Date.now();
      trackEvent(GA4.STREAM_START, { chat_id: chatId });
    }

    // Stream completed successfully
    if (
      currentStatus === "ready" &&
      (previousStatus === "streaming" || previousStatus === "submitted")
    ) {
      const duration = streamStartTime ? Date.now() - streamStartTime : 0;
      const messageCount = chat.messages?.length ?? 0;
      trackEvent(GA4.STREAM_COMPLETE, { chat_id: chatId, message_count: messageCount, duration });
      streamStartTime = null;
    }

    // Stream errored
    if (
      currentStatus === "error" &&
      (previousStatus === "streaming" || previousStatus === "submitted")
    ) {
      trackEvent(GA4.STREAM_ERROR, {
        chat_id: chatId,
        error_message: chat.error?.message ?? "Unknown error",
      });
      streamStartTime = null;
    }

    previousStatus = currentStatus;
  });

  function setup() {
    userHasScrolled = false;

    setTimeout(() => {
      showContents = true;
    }, 100);
  }

  beforeNavigate(() => {
    showContents = false;
    // Abort active stream to free HTTP connection for the new page's loader.
    // Without this, browser connection limits (6 per origin in HTTP/1.1) cause
    // the navigation to block until the stream completes.
    chat.stop();
    // Also abort any pending resumeStream GET request (ai-sdk doesn't handle this)
    resumeAbortController?.abort();
    resumeAbortController = null;
  });

  afterNavigate(() => {
    // Only setup UI state here - stream resumption is handled by onMount.
    // Since {#key data.chatId} destroys/recreates this component on navigation,
    // onMount always fires for the new chat. Calling resumeStream() here too
    // would create duplicate SSE connections and exhaust browser connection limits.
    setup();
  });

  // Handle OAuth return flow on initial mount
  onMount(async () => {
    setup();

    // Resume any active stream for existing chats (initial load)
    if (!isNew) {
      try {
        await chat.resumeStream();
      } catch {
        // No active stream to resume - that's expected
      }
    }

    // Handle OAuth return flow
    const url = new URL(window.location.href);
    const credentialId = url.searchParams.get("credential_id");

    if (credentialId) {
      try {
        const result = await parseResult(
          client.link.v1.credentials[":id"].$get({ param: { id: credentialId } }),
        );

        if (result.ok) {
          const { provider } = result.data;
          chat.sendMessage({
            parts: [{ type: "data-credential-linked", data: { provider, displayName: provider } }],
          });
        }
      } catch (error) {
        console.error("Failed to fetch credential details:", error);
      } finally {
        // Clean URL params
        url.searchParams.delete("credential_id");
        window.history.replaceState({}, "", url.toString());
      }
    }
  });

  /**
   * Stop handler - calls DELETE endpoint to abort server-side stream, then stops client
   */
  async function handleStop() {
    trackEvent(GA4.STREAM_STOP);
    await fetch(`${getAtlasDaemonUrl()}/api/chat/${chatId}/stream`, { method: "DELETE" }).catch(
      () => {},
    );
    chat.stop();
  }

  let userHasScrolled = $state(false);
  let animationFrameId = $state<number | null>(null);

  // Handle Scrolling
  function handleScroll() {
    userHasScrolled = true;

    if (!scrollContainer) return;

    const { scrollTop, scrollHeight, clientHeight } = scrollContainer;
    const isAtBottom = Math.abs(scrollHeight - scrollTop - clientHeight) < 5;

    // If user scrolls away from bottom, mark as manually scrolled
    if (!isAtBottom) {
      userHasScrolled = true;
    }
    // If user scrolls back to bottom, reset the flag
    if (isAtBottom) {
      userHasScrolled = false;
    }
  }

  // Scroll to the bottom of the container
  function continuouslyScrollToBottom() {
    if (!scrollContainer) return;
    scrollContainer.scrollTop = scrollContainer.scrollHeight;
    animationFrameId = requestAnimationFrame(continuouslyScrollToBottom);
  }

  // Auto-scroll when new messages are added, unless user has manually scrolled
  $effect(() => {
    if (!showContents) return;

    if (userHasScrolled && animationFrameId) {
      cancelAnimationFrame(animationFrameId);
      animationFrameId = null;
    }
    if (!userHasScrolled && !animationFrameId) {
      animationFrameId = requestAnimationFrame(continuouslyScrollToBottom);
    }
  });

  // Scroll to the bottom of the container
  function scrollToBottom() {
    if (!scrollContainer) return;
    scrollContainer.scrollTop = scrollContainer.scrollHeight;
  }

  let actionsAfterLastUser = $state<{ parts: AtlasUIMessagePart[] }>({ parts: [] });

  $effect(() => {
    const lastAssistantMessage = (chat?.messages ?? []).findLast((msg) => msg.role === "assistant");

    // If no user message found, return empty
    if (!lastAssistantMessage) {
      actionsAfterLastUser = { parts: [] };
      return;
    }

    actionsAfterLastUser = { parts: lastAssistantMessage.parts };
  });

  let showDetails = new SvelteMap<string, boolean>();
</script>

<div class="chat" class:visible={showContents} class:new-chat={isNew}>
  <div class="main">
    <div
      class="messages"
      class:has-messages={(chat.messages?.length ?? 0) > 0}
      bind:this={scrollContainer}
      onscroll={handleScroll}
    >
      <div
        class="messages-container"
        style:--additional-padding="{textareaAdditionalSize}px"
        class:has-outline={chat.messages?.some((msg) =>
          msg.parts.some((part) => part.type === "data-outline-update"),
        )}
      >
        <div class="messages-inner">
          {#if (chat.messages?.length ?? 0) === 0}
            <div class="first-message">
              <p>What would you like to work on today?</p>
            </div>
          {:else if !isNew && title}
            <div class="first-message">
              <h2>{title}</h2>
            </div>
          {/if}

          {#each chat.messages ?? [] as messageContainer, index ((messageContainer.id, index))}
            {@const messages = messageContainer.parts
              .map((message) => formatMessage(messageContainer, message))
              .filter((part) => part !== undefined)}
            {#if messages.length > 0}
              <div class="message-parts">
                {#each messages as message, index (index)}
                  {#if message}
                    {#if message.type === "request"}
                      <Request {message} />
                    {:else if message.type === "text"}
                      <Response {message} parts={messageContainer.parts} />
                    {:else if message.type === "display_artifact" && message.artifactId}
                      <DisplayArtifact artifactId={message.artifactId} />
                    {:else if message.type === "workspace_planner"}
                      <WorkspacePlan
                        artifactId={message.artifactId}
                        onApprove={() => {
                          chat.sendMessage({ text: "Approve this plan and create a workspace" });
                        }}
                        onTest={() => {
                          chat.sendMessage({ text: "Test this plan and show me the result" });
                        }}
                      />
                    {:else if message.type === "connect_service" && message.provider}
                      <ConnectService provider={message.provider} {chat} />
                    {:else if message.type === "workspace_creator" && !message.output.result.isError}
                      <WorkspaceCreated output={message.output} />
                    {:else if message.type === "credential_linked"}
                      <CredentialLinked {message} />
                    {:else if message.type === "intent"}
                      <Intent {message} />
                    {:else if message.type === "error"}
                      <ErrorMessage {message} />
                    {/if}
                  {/if}
                {/each}
                {#if messageContainer.role === "assistant" && messageContainer.parts.some((part) => part.type === "text" && part.state === "done")}
                  <div class="show-details" class:open={showDetails.get(messageContainer.id)}>
                    <ShowDetails
                      open={showDetails.get(messageContainer.id) ?? false}
                      onclick={() => {
                        const status = showDetails.get(messageContainer.id) ?? false;
                        if (!status) {
                          trackEvent(GA4.SHOW_DETAILS_EXPAND);
                        }
                        showDetails.set(messageContainer.id, !status);
                      }}
                    />
                  </div>
                {/if}

                {#if showDetails.get(messageContainer.id)}
                  <Reasoning parts={messageContainer.parts} />
                {/if}
              </div>
            {/if}
          {/each}

          {#if chat.status === "streaming" || chat.status === "submitted"}
            <Progress actions={actionsAfterLastUser.parts} {turnStartedAt} />
          {/if}
        </div>

        <Outline
          messages={(chat.messages ?? [])
            .filter((msg) => msg.role === "assistant")
            .filter((msg) => msg.parts.some((part) => part.type === "data-outline-update"))}
        />
      </div>

      <div class="spacer"></div>

      <div
        class="interactive-container"
        role="region"
        aria-label="Drag and drop files to attach them to your conversation"
        class:has-outline={chat.messages?.some((msg) =>
          msg.parts.some((part) => part.type === "data-outline-update"),
        )}
        ondragover={(e) => e.preventDefault()}
        ondrop={(e) => {
          e.preventDefault();
          handleFileDrop(
            appCtx,
            Array.from(e.dataTransfer?.files ?? []),
            isNew ? undefined : chatId,
          );
        }}
      >
        <div class="interactive-container-int">
          <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
          <form
            bind:this={form}
            onkeydown={(e) => {
              if (e.key === "Enter" && !e.shiftKey && !e.altKey) {
                e.preventDefault();
                e.currentTarget?.requestSubmit();
              }
            }}
            onsubmit={async (e) => {
              e.preventDefault();

              // Check if still uploading
              const hasUploadingFiles = Array.from(appCtx.stagedFiles.state.values()).some(
                (f) => f.status === "uploading",
              );
              if (hasUploadingFiles) return;

              if (chat && message.trim()) {
                // Build message with ready attachments only
                let combinedMessage = message;
                const readyFiles = Array.from(appCtx.stagedFiles.state.values()).filter(
                  (f) => f.status === "ready" && f.artifactId,
                );

                if (readyFiles.length > 0) {
                  combinedMessage += "\n\nAttachments:";
                  for (const file of readyFiles) {
                    combinedMessage += `\n- artifact:${file.artifactId}`;
                  }
                }

                trackEvent(GA4.MESSAGE_SEND, { is_new: isNew });
                chat.sendMessage({ text: combinedMessage });
                message = "";
                appCtx.stagedFiles.clear();

                userHasScrolled = false;
                scrollToBottom();
              }
            }}
          >
            {#if appCtx.stagedFiles.state.size > 0}
              <div class="staged-files">
                {#each appCtx.stagedFiles.state.entries() as [itemId, file] (itemId)}
                  <button
                    class="staged-file"
                    class:uploading={file.status === "uploading"}
                    class:ready={file.status === "ready"}
                    class:error={file.status === "error"}
                    title={file.error || file.name}
                    onclick={() => {
                      if (file.status !== "uploading") {
                        trackEvent(GA4.FILE_REMOVE);
                        appCtx.stagedFiles.remove(itemId);
                      }
                    }}
                    disabled={file.status === "uploading"}
                  >
                    {#if file.status === "uploading"}
                      <span class="status-icon spinning"><IconSmall.Progress /></span>
                    {:else if file.status === "ready"}
                      <span class="status-icon"><IconSmall.Check /></span>
                    {:else if file.status === "error"}
                      <span class="status-icon"><IconSmall.InfoCircled /></span>
                    {/if}

                    <span class="file-name">{file.name}</span>

                    {#if file.status === "error"}
                      <span class="error-text">{file.error}</span>
                    {:else}
                      <span class="file-size">{formatFileSize(file.size)}</span>
                    {/if}

                    {#if file.status !== "uploading"}
                      <span class="close-button">
                        <IconSmall.Close />
                      </span>
                    {/if}
                  </button>
                {/each}
              </div>
            {/if}

            <div class="textarea-container">
              <div class="actions">
                <DropdownMenu.Root
                  positioning={{
                    placement: "top-start",
                    gutter: 0,
                    offset: { crossAxis: -6, mainAxis: 12 },
                  }}
                >
                  {#snippet children(open)}
                    <DropdownMenu.Trigger>
                      <div class="action-trigger">
                        <Icons.Plus />
                      </div>
                    </DropdownMenu.Trigger>
                    <DropdownMenu.Content>
                      <DropdownMenu.Item
                        closeOnClick={false}
                        fileInput={{
                          onchange: (files) => {
                            trackEvent(GA4.FILE_ATTACH, { file_count: files.length });
                            handleFileDrop(appCtx, files);
                            open.set(false);
                          },
                          multiple: true,
                        }}
                      >
                        Add Files
                      </DropdownMenu.Item>

                      {#if !isNew && (chat.messages?.length ?? 0) > 0}
                        <DropdownMenu.Item
                          onclick={async () => {
                            trackEvent(GA4.SHARE_CHAT_CLICK, {
                              chat_id: chatId,
                              source: "chat_input_menu",
                            });
                            if (chat.messages) {
                              await shareChat(chat.messages, title);
                            }
                          }}
                        >
                          Share
                        </DropdownMenu.Item>
                      {/if}

                      <DropdownMenu.Separator />

                      <DropdownMenu.Item
                        onclick={() => {
                          trackEvent(GA4.NEW_CHAT_CLICK, { source: "chat_input_menu" });
                          goto("/chat");
                        }}
                      >
                        New Chat
                      </DropdownMenu.Item>
                    </DropdownMenu.Content>
                  {/snippet}
                </DropdownMenu.Root>
              </div>

              <Textarea
                name="message"
                placeholder="Type here..."
                value={message}
                onTextChange={(value) => {
                  message = value;
                }}
                onResize={(value) => {
                  textareaAdditionalSize = value - 40;
                }}
              />

              <div class="form-action">
                {#if chat.status === "streaming" || chat.status === "submitted"}
                  <button
                    class="stop-process"
                    type="button"
                    onclick={async (e) => {
                      e.preventDefault();
                      await handleStop();
                    }}
                  >
                    <IconSmall.Stop />
                  </button>
                {:else}
                  {@const hasUploadingFiles = Array.from(appCtx.stagedFiles.state.values()).some(
                    (f) => f.status === "uploading",
                  )}
                  <button type="submit" aria-label="Send message" disabled={hasUploadingFiles}>
                    <Icons.ArrowUp />
                  </button>
                {/if}
              </div>
            </div>
          </form>
        </div>

        {#if isNew && (chat.messages?.length ?? 0) === 0 && (chatsQuery.data?.chats ?? []).length > 0}
          <div class="recent-conversations" class:open={showChats}>
            <button
              class="toggle-chats"
              onclick={() => {
                if (!showChats) {
                  trackEvent(GA4.RECENT_CONVERSATIONS_EXPAND);
                }
                showChats = !showChats;
              }}
            >
              Recent Conversations <IconSmall.CaretRight />
            </button>
            {#if showChats}
              <div class="chat-list" transition:slide={{ duration: 200, easing: circOut }}>
                {#each (chatsQuery.data?.chats ?? []).slice(0, 5) as recentChat (recentChat.id)}
                  <a
                    class="chat-item"
                    href="/chat/{recentChat.id}"
                    onclick={() =>
                      trackEvent(GA4.RECENT_CONVERSATION_SELECT, { chat_id: recentChat.id })}
                  >
                    <span class="chat--title">{recentChat.title || "(Untitled)"}</span>
                    <span
                      class="chat--date"
                      title={new Date(recentChat.updatedAt).toLocaleString()}
                    >
                      {formatChatDate(recentChat.updatedAt)}
                    </span>
                  </a>
                {/each}
              </div>
            {/if}
          </div>
        {/if}
      </div>

      <ChatBufferBlur />
    </div>

    {#if isNew && (chat.messages?.length ?? 0) === 0}
      <footer>
        <span>Made By Tempest</span>
      </footer>
    {/if}
  </div>
</div>

<style>
  .chat {
    block-size: 100%;
    display: grid;
    grid-template-columns: 1fr;
    inline-size: 100%;
    overflow: hidden;
    opacity: 0;
    position: relative;
    transition: all 200ms ease;
    z-index: var(--layer-0);

    &.visible {
      opacity: 1;
    }
  }

  .main {
    display: flex;
    block-size: 100%;
    overflow: hidden;
    flex-direction: column;
    position: relative;
  }

  .first-message {
    p {
      font-size: var(--font-size-8);
      font-weight: var(--font-weight-5);
      text-align: center;
      opacity: 0.8;
    }

    h2 {
      font-size: var(--font-size-8);
      font-weight: var(--font-weight-6);
      line-height: var(--font-lineheight-1);
      margin-block-end: var(--size-2);
    }
  }

  .messages {
    block-size: 100%;
    display: flex;
    flex-direction: column;
    overflow-y: scroll;
    scroll-padding: 100px;
    padding-block: 0 var(--size-16);
    position: relative;
    scrollbar-width: thin;
  }

  .spacer {
    flex: 1;

    .new-chat .messages:not(.has-messages) & {
      flex: 0 1;
    }

    .new-chat .messages.has-messages & {
      flex: 1;
    }
  }

  .messages-container {
    display: grid;
    grid-template-columns: 1fr 0;
    padding-block: var(--size-10) calc(var(--size-16) + var(--additional-padding, 0));
    transition:
      grid-template-columns 450ms ease-in-out,
      gap 450ms ease-in-out;

    .new-chat & {
      margin-block-start: auto;
      padding-block-end: var(--size-6);
    }

    &.has-outline {
      grid-template-columns: 1fr var(--size-56);
    }
  }

  .message-parts {
    display: flex;
    flex-direction: column;
    inline-size: 100%;
    gap: var(--size-4);
  }

  .show-details {
    opacity: 0;
    visibility: hidden;
    transition: opacity 250ms ease;
  }

  .message-parts:hover .show-details,
  .show-details.open {
    opacity: 1;
    visibility: visible;
  }

  .messages-inner {
    display: flex;
    flex-direction: column;
    inline-size: 100%;
    gap: var(--size-8);
    margin: 0 auto;
    max-inline-size: var(--size-272);
    overflow: hidden;
    padding-inline: var(--size-16);
  }

  footer {
    font-size: var(--font-size-2);
    font-weight: var(--font-weight-5);
    opacity: 0.5;
    margin-block-start: auto;
    text-align: center;
    padding-block-end: var(--size-7);
    position: absolute;
    inset-block-end: 0;
    inset-inline: 0;
    z-index: var(--layer-1);
  }

  .interactive-container {
    --local__translate-y: var(--size-4);
    inset-block-end: var(--size-16);
    inset-inline-start: calc(var(--size-56));
    inset-inline-end: var(--size-1-5);
    position: fixed;
    transition: all 450ms ease-in-out;
    z-index: var(--layer-2);

    .new-chat & {
      inline-size: 100%;
      position: sticky;
      inset-block-end: 0;
      inset-inline-start: unset;
      inset-inline-end: unset;
      margin-block-end: auto;
      margin-inline: auto;
      max-inline-size: var(--size-160);
      padding-inline: var(--size-8);
    }

    .new-chat .messages.has-messages & {
      transform: translateY(var(--local__translate-y));
      transition: transform 450ms ease-in-out;
    }

    &.has-outline {
      inset-inline-end: calc(var(--size-56));

      .new-chat & {
        --local__translate-x: calc(-1 * calc(var(--size-28) + var(--size-6)));
        transition: transform 450ms ease-in-out;
      }
    }

    .interactive-container-int {
      margin-inline: auto;
      max-inline-size: var(--size-160);
      padding-inline: var(--size-8);

      .new-chat & {
        max-inline-size: unset;
        padding-inline: unset;
      }
    }

    form {
      background-color: var(--color-surface-1);
      border-radius: var(--radius-5);
      box-shadow: var(--shadow-1);
      display: flex;
      flex-direction: column;
      position: relative;
      padding-inline: var(--size-3) var(--size-1-5);

      .form-action {
        display: flex;
        margin-block-end: var(--size-1-5);
      }

      button[type="submit"],
      .stop-process {
        align-items: center;
        background-color: var(--color-yellow);
        block-size: var(--size-7);
        border-radius: var(--radius-4);
        color: var(--color-white);
        display: flex;
        justify-content: center;
        inline-size: var(--size-7);
        transition: all 200ms ease;

        &:hover:not(:disabled) {
          background-color: var(--color-text);
          @media (prefers-color-scheme: dark) {
            color: var(--color-surface-1);
          }
        }

        &:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }
      }

      .textarea-container {
        align-items: end;
        display: flex;
        gap: var(--size-1);
      }

      .actions {
        display: flex;
        margin-block-end: var(--size-1-5);
      }

      .action-trigger {
        align-items: center;
        block-size: var(--size-7);
        border-radius: var(--radius-4);
        color: color-mix(in srgb, var(--color-text), transparent 30%);
        display: flex;
        justify-content: center;
        inline-size: var(--size-7);
        transition: all 200ms ease;

        &:hover,
        :global(:focus-visible) & {
          background-color: var(--color-surface-2);
        }
      }
    }
  }

  .staged-files {
    display: flex;
    flex-wrap: wrap;
    gap: var(--size-1);
    inline-size: 100%;
    padding-block-start: var(--size-2);
    margin-inline-start: calc(-1 * var(--size-0-5));

    .staged-file {
      align-items: center;
      block-size: var(--size-5-5);
      border-radius: var(--radius-2-5);
      border: var(--size-px) solid var(--color-border-1);
      cursor: pointer;
      display: flex;
      font-size: var(--font-size-1);
      font-weight: var(--font-weight-5);
      gap: var(--size-0-5);
      justify-content: center;
      max-inline-size: var(--size-56);
      padding-inline: var(--size-1);
      overflow: hidden;
      text-align: left;
      transition: all 150ms ease;

      &.uploading {
        opacity: 0.7;
        cursor: wait;
      }

      &.ready {
        border-color: var(--color-success, #22c55e);

        .status-icon {
          color: var(--color-success, #22c55e);
        }
      }

      &.error {
        border-color: var(--color-error, #ef4444);
        color: var(--color-error, #ef4444);

        .status-icon {
          color: var(--color-error, #ef4444);
        }
      }

      .status-icon {
        flex: none;
        display: flex;
        align-items: center;

        &.spinning {
          animation: spin 1s linear infinite;
        }
      }

      .file-name {
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
        flex: 1;
        opacity: 0.7;
      }

      .file-size {
        font-size: var(--font-size-0);
        opacity: 0.5;
        flex: none;
      }

      .error-text {
        font-size: var(--font-size-0);
        opacity: 0.8;
        flex: none;
        max-inline-size: var(--size-24);
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
      }

      .close-button {
        border-radius: var(--radius-2);
        block-size: var(--size-4);
        flex: none;
        inline-size: var(--size-4);
        transition: all 150ms ease;
      }

      &:hover .close-button {
        background-color: var(--color-surface-2);
      }
    }
  }

  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }

  .recent-conversations {
    padding-inline: var(--size-4);
    padding-block-start: var(--size-3-5);

    .toggle-chats {
      align-items: center;
      display: flex;
      gap: var(--size-1);
      font-size: var(--font-size-3);
      font-weight: var(--font-weight-5);
      opacity: 0.5;
      padding-block-end: var(--size-3);

      .open & :global(svg) {
        transform: rotate(90deg);
      }
    }

    .chat-list {
      a {
        border-block-start: 1px solid color-mix(in srgb, var(--color-border-1) 50%, transparent);
        display: flex;
        justify-content: space-between;
        inline-size: 100%;
        padding-block: var(--size-3);
      }
    }

    .chat--title {
      font-size: var(--font-size-3);
      font-weight: var(--font-weight-5);
      opacity: 0.7;
    }

    .chat--date {
      font-size: var(--font-size-2);
      font-weight: var(--font-weight-5);
      opacity: 0.5;
    }
  }
</style>
