package service

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tempestteam/atlas/apps/cortex/repo"
	"github.com/tempestteam/atlas/pkg/x/middleware/jwt"
)

func (s *Service) HandleUpload(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	userID, err := jwt.MustGetUserID(ctx)
	if err != nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	// Acquire semaphore slot for upload (prevents memory exhaustion)
	select {
	case s.uploadSem <- struct{}{}:
		defer func() { <-s.uploadSem }()
	default:
		s.Logger.Warn("upload rejected: too many concurrent uploads", "user_id", userID)
		http.Error(w, "Server busy, please try again", http.StatusServiceUnavailable)
		return
	}

	// Limit request body size
	r.Body = http.MaxBytesReader(w, r.Body, s.config.MaxUploadSize)

	// Read entire body into memory to get accurate size
	body, err := io.ReadAll(r.Body)
	if err != nil {
		s.Logger.Error("failed to read body", "error", err)
		http.Error(w, "Failed to read request body", http.StatusBadRequest)
		return
	}

	contentSize := int64(len(body))

	// Create database record FIRST to prevent orphaned blobs
	// ID generated by Postgres, uses RLS-scoped transaction for user isolation
	pgID, err := withUserContextRead(ctx, userID, func(q *repo.Queries) (pgtype.UUID, error) {
		return q.CreateObject(ctx, repo.CreateObjectParams{
			UserID:      userID,
			ContentSize: pgtype.Int8{Int64: contentSize, Valid: true},
			Metadata:    []byte("{}"),
		})
	})
	if err != nil {
		s.Logger.Error("failed to create object record", "error", err)
		http.Error(w, "Failed to create object", http.StatusInternalServerError)
		return
	}

	id := uuid.UUID(pgID.Bytes)

	// Upload to GCS after DB record exists
	storage, err := StorageFromContext(ctx)
	if err != nil {
		s.Logger.Error("failed to get storage", "error", err)
		http.Error(w, "Internal error", http.StatusInternalServerError)
		return
	}

	if err := storage.Upload(ctx, id, bytes.NewReader(body)); err != nil {
		s.Logger.Error("upload failed", "error", err, "id", id)
		// DB record exists but upload failed - could implement cleanup here
		// For now, the record will exist with no blob (could be fixed by retry)
		http.Error(w, "Upload failed", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(map[string]string{"id": id.String()}); err != nil {
		s.Logger.Error("failed to encode response", "error", err)
	}
}

func (s *Service) HandleUpdate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	idStr := chi.URLParam(r, "id")

	userID, err := jwt.MustGetUserID(ctx)
	if err != nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	id, err := uuid.Parse(idStr)
	if err != nil {
		http.Error(w, "Invalid ID", http.StatusBadRequest)
		return
	}

	// Verify object exists and user owns it (RLS enforces user isolation)
	pgID := pgtype.UUID{Bytes: id, Valid: true}
	_, err = withUserContextRead(ctx, userID, func(q *repo.Queries) (repo.CortexObject, error) {
		return q.GetObjectForUser(ctx, repo.GetObjectForUserParams{
			ID:     pgID,
			UserID: userID,
		})
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			http.Error(w, "Object not found", http.StatusNotFound)
			return
		}
		s.Logger.Error("failed to get object", "error", err, "id", id)
		http.Error(w, "Internal error", http.StatusInternalServerError)
		return
	}

	// Acquire semaphore slot for upload (prevents memory exhaustion)
	select {
	case s.uploadSem <- struct{}{}:
		defer func() { <-s.uploadSem }()
	default:
		s.Logger.Warn("update rejected: too many concurrent uploads", "user_id", userID, "object_id", id)
		http.Error(w, "Server busy, please try again", http.StatusServiceUnavailable)
		return
	}

	// Limit request body size
	r.Body = http.MaxBytesReader(w, r.Body, s.config.MaxUploadSize)

	// Read entire body into memory to get accurate size
	body, err := io.ReadAll(r.Body)
	if err != nil {
		s.Logger.Error("failed to read body", "error", err, "id", id)
		http.Error(w, "Failed to read request body", http.StatusBadRequest)
		return
	}

	contentSize := int64(len(body))

	// Upload to GCS (GCS versioning handles history automatically)
	storage, err := StorageFromContext(ctx)
	if err != nil {
		s.Logger.Error("failed to get storage", "error", err)
		http.Error(w, "Internal error", http.StatusInternalServerError)
		return
	}

	if err := storage.Upload(ctx, id, bytes.NewReader(body)); err != nil {
		s.Logger.Error("update upload failed", "error", err, "id", id)
		http.Error(w, "Upload failed", http.StatusInternalServerError)
		return
	}

	// Update content size after successful upload (RLS enforces user isolation)
	err = withUserContext(ctx, userID, func(q *repo.Queries) error {
		return q.UpdateContentSize(ctx, repo.UpdateContentSizeParams{
			ID:          pgID,
			ContentSize: pgtype.Int8{Int64: contentSize, Valid: true},
		})
	})
	if err != nil {
		s.Logger.Error("failed to update content size", "error", err, "id", id)
		http.Error(w, "Failed to update object", http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusOK)
}
