<script lang="ts">
  import { Chat } from "@ai-sdk/svelte";
  import type { AtlasUIMessage, AtlasUIMessagePart } from "@atlas/agent-sdk";
  import { GA4, trackApiError, trackEvent, trackNetworkError } from "@atlas/analytics/ga4";
  import { client, parseResult } from "@atlas/client/v2";
  import type { ArtifactWithContents } from "@atlas/core/artifacts";
  import { getAtlasDaemonUrl } from "@atlas/oapi-client";
  import { useQueryClient } from "@tanstack/svelte-query";
  import { afterNavigate, beforeNavigate, goto } from "$app/navigation";
  import { getAppContext, handleFileDrop, isFileInProgress } from "$lib/app-context.svelte";
  import ChatBufferBlur from "$lib/components/chat-buffer-blur.svelte";
  import DisplayArtifact from "$lib/modules/artifacts/display.svelte";
  import WorkspacePlan from "$lib/modules/artifacts/workspace-plan.svelte";
  import MessageForm from "$lib/modules/conversation/message-form.svelte";
  import Outline from "$lib/modules/conversation/outline.svelte";
  import ArtifactAttached from "$lib/modules/messages/artifact-attached.svelte";
  import ConnectService from "$lib/modules/messages/connect-service.svelte";
  import CredentialLinked from "$lib/modules/messages/credential-linked.svelte";
  import ErrorMessage from "$lib/modules/messages/error-message.svelte";
  import { formatMessage } from "$lib/modules/messages/format";
  import Intent from "$lib/modules/messages/intent.svelte";
  import Progress from "$lib/modules/messages/progress.svelte";
  import Reasoning from "$lib/modules/messages/reasoning.svelte";
  import Request from "$lib/modules/messages/request.svelte";
  import Response from "$lib/modules/messages/response.svelte";
  import ShowDetails from "$lib/modules/messages/show-details.svelte";
  import WorkspaceCreated from "$lib/modules/messages/workspace-created.svelte";
  import { getDatetimeContext } from "$lib/utils/date";
  import { DefaultChatTransport } from "ai";
  import { onMount, setContext } from "svelte";
  import { SvelteMap } from "svelte/reactivity";
  import Breadcrumbs from "./breadcrumbs.svelte";

  /**
   * ChatSession component - handles a single chat instance.
   *
   * This component persists across chat navigations. When chatId changes,
   * $derived blocks recreate the Chat and transport instances. The
   * beforeNavigate guard skips cleanup for programmatic goto() calls.
   */

  interface Props {
    /** Chat ID - always a string, generated by loader for new chats */
    chatId: string;
    /** Chat title (undefined for new chats) */
    title: string | undefined;
    /** Initial messages from loader */
    initialMessages: AtlasUIMessage[];
    /** Pre-fetched artifacts map */
    artifacts: Map<string, ArtifactWithContents>;
  }

  const { chatId, title, initialMessages, artifacts }: Props = $props();

  // Expose artifacts map to child components via context
  const ARTIFACTS_KEY = Symbol.for("artifacts");
  setContext(ARTIFACTS_KEY, artifacts);

  const appCtx = getAppContext();
  const queryClient = useQueryClient();

  let message = $state<string>("");
  let textareaAdditionalSize = $state(1);

  // Follow scroll handling
  let scrollContainer = $state<HTMLDivElement | null>(null);
  let showContents = $state(false);

  // Track whether we've already updated the URL for this new chat
  let hasUpdatedUrl = $state(false);

  // AbortController for resumeStream GET requests. The ai-sdk doesn't pass
  // abortSignal to reconnectToStream, so we inject it via our fetch wrapper.
  // This prevents connection leaks when navigating away during stream resume.
  let resumeAbortController = $state<AbortController | null>(null);

  // Server-provided turn start timestamp for accurate timer display after refresh
  let turnStartedAt = $state<number | null>(null);

  // Track stream timing for analytics
  let streamStartTime = $state<number | null>(null);
  let previousStatus = $state<string | null>(null);

  const transport = $derived(
    new DefaultChatTransport({
      api: `${getAtlasDaemonUrl()}/api/chat`,
      /**
       * Custom fetch wrapper that:
       * 1. Updates URL when new chat is created (POST succeeds)
       * 2. Injects AbortSignal into GET requests (resumeStream) since ai-sdk
       *    doesn't pass one, causing connection leaks on navigation
       */
      fetch: async (url, init): Promise<globalThis.Response> => {
        // Clear stale timestamp at start of new request so Progress mounts fresh
        if (init?.method === "POST") {
          turnStartedAt = null;
        }

        // For GET requests (resumeStream), inject our abort controller's signal
        // since ai-sdk's reconnectToStream doesn't pass abortSignal to fetch
        if (init?.method === "GET" || !init?.method) {
          resumeAbortController = new AbortController();
          init = { ...init, signal: resumeAbortController.signal };
        }

        let response: globalThis.Response;
        try {
          response = await fetch(url, init);
        } catch (error) {
          // Track network errors (connection failures, timeouts, etc.)
          const message = error instanceof Error ? error.message : "Network error";
          // Don't track aborted requests (user navigated away)
          if (!(error instanceof DOMException && error.name === "AbortError")) {
            trackNetworkError(String(url), message, init?.method ?? "GET");
          }
          throw error;
        }

        // Track API errors (non-2xx responses)
        if (!response.ok) {
          const errorText = await response
            .clone()
            .text()
            .catch(() => "Unknown error");
          trackApiError(String(url), response.status, errorText, init?.method ?? "GET");
        }

        // Capture server-provided turn start time for accurate timer display
        const startedAt = response.headers.get("X-Turn-Started-At");
        if (startedAt) {
          turnStartedAt = parseInt(startedAt, 10);
        }

        // Refresh sidebar on every successful message (chat's updatedAt changes)
        if (init?.method === "POST" && response.ok) {
          queryClient.invalidateQueries({ queryKey: ["chats"], refetchType: "all" });
          // Update URL for new chats (only once)
          // TODO: not sure we need this anymore
          if (!hasUpdatedUrl) {
            hasUpdatedUrl = true;
            goto(`/chat/${chatId}`, { replaceState: true });
          }
        }

        return response;
      },
      prepareSendMessagesRequest({ messages, id }) {
        return { body: { message: messages.at(-1), id, datetime: getDatetimeContext() } };
      },
    }),
  );

  // Create Chat instance once - no reactive recreation
  // chatId is immutable for this component's lifetime
  const chat = $derived(
    new Chat<AtlasUIMessage>({ id: chatId, messages: initialMessages, transport }),
  );

  // Track streaming lifecycle for analytics
  $effect(() => {
    const currentStatus = chat.status;

    // Stream started
    if (
      (currentStatus === "streaming" || currentStatus === "submitted") &&
      previousStatus !== "streaming" &&
      previousStatus !== "submitted"
    ) {
      streamStartTime = Date.now();
      trackEvent(GA4.STREAM_START, { chat_id: chatId });
    }

    // Stream completed successfully
    if (
      currentStatus === "ready" &&
      (previousStatus === "streaming" || previousStatus === "submitted")
    ) {
      const duration = streamStartTime ? Date.now() - streamStartTime : 0;
      const messageCount = chat.messages?.length ?? 0;
      trackEvent(GA4.STREAM_COMPLETE, { chat_id: chatId, message_count: messageCount, duration });
      streamStartTime = null;
    }

    // Stream errored
    if (
      currentStatus === "error" &&
      (previousStatus === "streaming" || previousStatus === "submitted")
    ) {
      trackEvent(GA4.STREAM_ERROR, {
        chat_id: chatId,
        error_message: chat.error?.message ?? "Unknown error",
      });
      streamStartTime = null;
    }

    previousStatus = currentStatus;
  });

  function setup() {
    userHasScrolled = false;

    setTimeout(() => {
      showContents = true;
    }, 100);
  }

  async function reconnect() {
    // Resume any active stream for existing chats (initial load)

    try {
      await chat.resumeStream();
    } catch {
      // No active stream to resume - that's expected
    }

    // Handle OAuth return flow
    const url = new URL(window.location.href);
    const credentialId = url.searchParams.get("credential_id");

    if (credentialId) {
      try {
        const result = await parseResult(
          client.link.v1.credentials[":id"].$get({ param: { id: credentialId } }),
        );

        if (result.ok) {
          const { provider } = result.data;
          chat.sendMessage({
            parts: [{ type: "data-credential-linked", data: { provider, displayName: provider } }],
          });
        }
      } catch (error) {
        console.error("Failed to fetch credential details:", error);
      } finally {
        // Clean URL params
        url.searchParams.delete("credential_id");
        window.history.replaceState({}, "", url.toString());
      }
    }
  }

  beforeNavigate((navigation) => {
    if (navigation.type === "goto") return;
    showContents = false;
    // Abort active stream to free HTTP connection for the new page's loader.
    // Without this, browser connection limits (6 per origin in HTTP/1.1) cause
    // the navigation to block until the stream completes.
    chat.stop();
    // Also abort any pending resumeStream GET request (ai-sdk doesn't handle this)
    resumeAbortController?.abort();
    resumeAbortController = null;
  });

  afterNavigate(() => {
    setup();
    reconnect();
  });

  // Handle OAuth return flow on initial mount
  onMount(() => {
    setup();
    reconnect();
  });

  /**
   * Stop handler - calls DELETE endpoint to abort server-side stream, then stops client
   */
  async function handleStop() {
    trackEvent(GA4.STREAM_STOP);
    await fetch(`${getAtlasDaemonUrl()}/api/chat/${chatId}/stream`, { method: "DELETE" }).catch(
      () => {},
    );
    chat.stop();
  }

  let userHasScrolled = $state(false);
  let animationFrameId = $state<number | null>(null);

  // Handle Scrolling
  function handleScroll() {
    userHasScrolled = true;

    if (!scrollContainer) return;

    const { scrollTop, scrollHeight, clientHeight } = scrollContainer;
    const isAtBottom = Math.abs(scrollHeight - scrollTop - clientHeight) < 5;

    // If user scrolls away from bottom, mark as manually scrolled
    if (!isAtBottom) {
      userHasScrolled = true;
    }
    // If user scrolls back to bottom, reset the flag
    if (isAtBottom) {
      userHasScrolled = false;
    }
  }

  // Scroll to the bottom of the container
  function continuouslyScrollToBottom() {
    if (!scrollContainer) return;
    scrollContainer.scrollTop = scrollContainer.scrollHeight;
    animationFrameId = requestAnimationFrame(continuouslyScrollToBottom);
  }

  // Auto-scroll when new messages are added, unless user has manually scrolled
  $effect(() => {
    if (!showContents) return;

    if (userHasScrolled && animationFrameId) {
      cancelAnimationFrame(animationFrameId);
      animationFrameId = null;
    }

    if (!userHasScrolled && !animationFrameId) {
      animationFrameId = requestAnimationFrame(continuouslyScrollToBottom);
    }
  });

  // Scroll to the bottom of the container
  function scrollToBottom() {
    if (!scrollContainer) return;
    scrollContainer.scrollTop = scrollContainer.scrollHeight;
  }

  let actionsAfterLastUser = $state<{ parts: AtlasUIMessagePart[] }>({ parts: [] });

  $effect(() => {
    const lastAssistantMessage = (chat?.messages ?? []).findLast((msg) => msg.role === "assistant");

    // If no user message found, return empty
    if (!lastAssistantMessage) {
      actionsAfterLastUser = { parts: [] };
      return;
    }

    actionsAfterLastUser = { parts: lastAssistantMessage.parts };
  });

  let showDetails = new SvelteMap<string, boolean>();
</script>

<div class="chat" class:visible={showContents}>
  <div class="main">
    <div
      class="messages"
      class:has-messages={(chat.messages?.length ?? 0) > 0}
      bind:this={scrollContainer}
      onscroll={handleScroll}
    >
      <Breadcrumbs {title} />

      <div
        class="messages-container"
        style:--additional-padding="{textareaAdditionalSize}px"
        class:has-outline={chat.messages?.some((msg) =>
          msg.parts.some((part) => part.type === "data-outline-update"),
        )}
      >
        <div class="messages-inner">
          {#each chat.messages ?? [] as messageContainer, index ((messageContainer.id, index))}
            {@const messages = messageContainer.parts
              .map((message) => formatMessage(messageContainer, message))
              .filter((part) => part !== undefined)}
            {#if messages.length > 0}
              <div class="message-parts">
                {#each messages as message, index (index)}
                  {#if message}
                    {#if message.type === "request"}
                      <Request {message} />
                    {:else if message.type === "text"}
                      <Response {message} parts={messageContainer.parts} />
                    {:else if message.type === "display_artifact" && message.artifactId}
                      <DisplayArtifact artifactId={message.artifactId} />
                    {:else if message.type === "workspace_planner"}
                      <WorkspacePlan
                        artifactId={message.artifactId}
                        onApprove={() => {
                          chat.sendMessage({ text: "Approve this plan and create a workspace" });
                        }}
                        onTest={() => {
                          chat.sendMessage({ text: "Test this plan and show me the result" });
                        }}
                      />
                    {:else if message.type === "connect_service" && message.provider}
                      <ConnectService provider={message.provider} {chat} />
                    {:else if message.type === "workspace_creator" && !message.output.result.isError}
                      <WorkspaceCreated output={message.output} />
                    {:else if message.type === "credential_linked"}
                      <CredentialLinked {message} />
                    {:else if message.type === "artifact_attached"}
                      <ArtifactAttached {message} />
                    {:else if message.type === "intent"}
                      <Intent {message} />
                    {:else if message.type === "error"}
                      <ErrorMessage {message} />
                    {/if}
                  {/if}
                {/each}
                {#if messageContainer.role === "assistant" && messageContainer.parts.some((part) => part.type === "text" && part.state === "done")}
                  <div class="show-details" class:open={showDetails.get(messageContainer.id)}>
                    <ShowDetails
                      open={showDetails.get(messageContainer.id) ?? false}
                      onclick={() => {
                        const status = showDetails.get(messageContainer.id) ?? false;
                        if (!status) {
                          trackEvent(GA4.SHOW_DETAILS_EXPAND);
                        }
                        showDetails.set(messageContainer.id, !status);
                      }}
                    />
                  </div>
                {/if}

                {#if showDetails.get(messageContainer.id)}
                  <Reasoning parts={messageContainer.parts} />
                {/if}
              </div>
            {/if}
          {/each}

          {#if chat.status === "streaming" || chat.status === "submitted"}
            <Progress actions={actionsAfterLastUser.parts} {turnStartedAt} />
          {/if}
        </div>

        <Outline
          messages={(chat.messages ?? [])
            .filter((msg) => msg.role === "assistant")
            .filter((msg) => msg.parts.some((part) => part.type === "data-outline-update"))}
        />
      </div>

      <div class="spacer"></div>

      <div
        class="interactive-container"
        role="region"
        aria-label="Drag and drop files to attach them to your conversation"
        class:has-outline={chat.messages?.some((msg) =>
          msg.parts.some((part) => part.type === "data-outline-update"),
        )}
        ondragover={(e) => e.preventDefault()}
        ondrop={(e) => {
          e.preventDefault();
          handleFileDrop(appCtx, Array.from(e.dataTransfer?.files ?? []), chatId);
        }}
      >
        <div class="interactive-container-int">
          <MessageForm
            isDisabled={Array.from(appCtx.stagedFiles.state.values()).some((f) =>
              isFileInProgress(f),
            )}
            {chatId}
            bind:message
            bind:textareaAdditionalSize
            onSubmit={(message) => {
              // Check if still uploading
              const hasUploadingFiles = Array.from(appCtx.stagedFiles.state.values()).some((f) =>
                isFileInProgress(f),
              );

              if (hasUploadingFiles) return;

              if (chat && message.trim()) {
                const readyFiles = Array.from(appCtx.stagedFiles.state.values()).filter(
                  (f) => f.status === "ready" && f.artifactId,
                );

                trackEvent(GA4.MESSAGE_SEND, { is_new: false });

                // Clear stale timestamp before sendMessage so Progress mounts fresh
                turnStartedAt = null;

                if (readyFiles.length > 0) {
                  // Send message with text AND artifact-attached data part
                  // The parts array includes both the user's text and the artifact metadata
                  chat.sendMessage({
                    parts: [
                      { type: "text", text: message },
                      {
                        type: "data-artifact-attached",
                        data: {
                          artifactIds: readyFiles
                            .map((f) => f.artifactId)
                            .filter((f) => f !== undefined),
                          filenames: readyFiles.map((f) => f.name),
                        },
                      },
                    ],
                  });
                } else {
                  // No attachments, send simple text message
                  chat.sendMessage({ text: message });
                }
                message = "";
                appCtx.stagedFiles.clear();

                userHasScrolled = false;
                scrollToBottom();
              }
            }}
            status={chat.status}
            onStop={async () => {
              await handleStop();
            }}
          />
        </div>
      </div>

      <ChatBufferBlur />
    </div>
  </div>
</div>

<style>
  .chat {
    block-size: 100%;
    display: grid;
    grid-template-columns: 1fr;
    inline-size: 100%;
    overflow: hidden;
    position: relative;
    opacity: 0;
    z-index: var(--layer-0);

    &.visible {
      opacity: 1;
    }
  }

  .main {
    display: flex;
    block-size: 100%;
    overflow: hidden;
    flex-direction: column;
    position: relative;
  }

  .messages {
    block-size: 100%;
    display: flex;
    flex-direction: column;
    overflow-y: scroll;
    padding-block: 0 var(--size-16);
    position: relative;
    scrollbar-width: thin;
  }

  .spacer {
    flex: 1;
  }

  .messages-container {
    display: grid;
    grid-template-columns: 1fr 0;
    padding-block: var(--size-10) calc(var(--size-16) + var(--additional-padding, 0));
    transition:
      grid-template-columns 450ms ease-in-out,
      gap 450ms ease-in-out;

    &.has-outline {
      grid-template-columns: 1fr var(--size-56);
    }
  }

  .message-parts {
    display: flex;
    flex-direction: column;
    inline-size: 100%;
    gap: var(--size-4);
  }

  .show-details {
    opacity: 0;
    visibility: hidden;
    transition: opacity 250ms ease;
  }

  .message-parts:hover .show-details,
  .show-details.open {
    opacity: 1;
    visibility: visible;
  }

  .messages-inner {
    display: flex;
    flex-direction: column;
    inline-size: 100%;
    gap: var(--size-8);
    margin: 0 auto;
    max-inline-size: var(--size-272);
    overflow: hidden;
    padding-inline: var(--size-16);
  }

  .interactive-container {
    --local__translate-y: var(--size-4);
    inset-block-end: var(--size-16);
    inset-inline-start: calc(var(--size-56));
    inset-inline-end: var(--size-1-5);
    position: fixed;
    transition: all 450ms ease-in-out;
    z-index: var(--layer-2);

    &.has-outline {
      inset-inline-end: calc(var(--size-56));
    }

    .interactive-container-int {
      margin-inline: auto;
      max-inline-size: var(--size-160);
      padding-inline: var(--size-8);
    }
  }
</style>
