<script lang="ts">
  import { Chat } from "@ai-sdk/svelte";
  import type { AtlasUIMessage } from "@atlas/agent-sdk";
  import { GA4, trackApiError, trackEvent, trackNetworkError } from "@atlas/analytics/ga4";
  import { client, parseResult } from "@atlas/client/v2";
  import type { ArtifactWithContents } from "@atlas/core/artifacts";
  import { getAtlasDaemonUrl } from "@atlas/oapi-client";
  import { useQueryClient } from "@tanstack/svelte-query";
  import { afterNavigate, beforeNavigate, goto } from "$app/navigation";
  import { getAppContext, handleFileDrop, isFileInProgress } from "$lib/app-context.svelte";
  import ChatBufferBlur from "$lib/components/chat-buffer-blur.svelte";
  import { Icons } from "$lib/components/icons";
  import Catalog from "$lib/modules/conversation/catalog.svelte";
  import MessageForm from "$lib/modules/conversation/message-form.svelte";
  import { getDatetimeContext } from "$lib/utils/date";
  import { DefaultChatTransport } from "ai";
  import { onMount, setContext } from "svelte";
  import { fade } from "svelte/transition";

  /**
   * ChatSession component - handles a single chat instance.
   *
   * This component persists across chat navigations. When chatId changes,
   * $derived blocks recreate the Chat and transport instances. The
   * beforeNavigate guard skips cleanup for programmatic goto() calls.
   */

  interface Props {
    /** Chat ID - always a string, generated by loader for new chats */
    chatId: string;
    /** Chat title (undefined for new chats) */
    title: string | undefined;
    /** Initial messages from loader */
    initialMessages: AtlasUIMessage[];
    /** Pre-fetched artifacts map */
    artifacts: Map<string, ArtifactWithContents>;
  }

  const { chatId, title, initialMessages, artifacts }: Props = $props();

  // Expose artifacts map to child components via context
  const ARTIFACTS_KEY = Symbol.for("artifacts");
  setContext(ARTIFACTS_KEY, artifacts);

  const appCtx = getAppContext();
  const queryClient = useQueryClient();

  let scrollContainer = $state<HTMLDivElement>();
  let message = $state<string>("");

  // Follow scroll handling
  let showContents = $state(false);

  // Track whether we've already updated the URL for this new chat
  let hasUpdatedUrl = $state(false);

  // AbortController for resumeStream GET requests. The ai-sdk doesn't pass
  // abortSignal to reconnectToStream, so we inject it via our fetch wrapper.
  // This prevents connection leaks when navigating away during stream resume.
  let resumeAbortController = $state<AbortController | null>(null);

  const transport = $derived(
    new DefaultChatTransport({
      api: `${getAtlasDaemonUrl()}/api/chat`,
      /**
       * Custom fetch wrapper that:
       * 1. Updates URL when new chat is created (POST succeeds)
       * 2. Injects AbortSignal into GET requests (resumeStream) since ai-sdk
       *    doesn't pass one, causing connection leaks on navigation
       */
      fetch: async (url, init): Promise<globalThis.Response> => {
        // For GET requests (resumeStream), inject our abort controller's signal
        // since ai-sdk's reconnectToStream doesn't pass abortSignal to fetch
        if (init?.method === "GET" || !init?.method) {
          resumeAbortController = new AbortController();
          init = { ...init, signal: resumeAbortController.signal };
        }

        let response: globalThis.Response;
        try {
          response = await fetch(url, init);
        } catch (error) {
          // Track network errors (connection failures, timeouts, etc.)
          const message = error instanceof Error ? error.message : "Network error";
          // Don't track aborted requests (user navigated away)
          if (!(error instanceof DOMException && error.name === "AbortError")) {
            trackNetworkError(String(url), message, init?.method ?? "GET");
          }
          throw error;
        }

        // Track API errors (non-2xx responses)
        if (!response.ok) {
          const errorText = await response
            .clone()
            .text()
            .catch(() => "Unknown error");
          trackApiError(String(url), response.status, errorText, init?.method ?? "GET");
        }

        // Refresh sidebar on every successful message (chat's updatedAt changes)
        if (init?.method === "POST" && response.ok) {
          queryClient.invalidateQueries({ queryKey: ["chats"], refetchType: "all" });
          // Update URL for new chats (only once)
          if (!hasUpdatedUrl) {
            hasUpdatedUrl = true;
            goto(`/chat/${chatId}`, { replaceState: true });
          }
        }

        return response;
      },
      prepareSendMessagesRequest({ messages, id }) {
        return { body: { message: messages.at(-1), id, datetime: getDatetimeContext() } };
      },
    }),
  );

  // Create Chat instance once - no reactive recreation
  // chatId is immutable for this component's lifetime
  const chat = $derived(
    new Chat<AtlasUIMessage>({ id: chatId, messages: initialMessages, transport }),
  );

  function setup() {
    hasUpdatedUrl = false;

    setTimeout(() => {
      showContents = true;
    }, 100);
  }

  async function reconnect() {
    // Handle OAuth return flow
    const url = new URL(window.location.href);
    const credentialId = url.searchParams.get("credential_id");

    if (credentialId) {
      try {
        const result = await parseResult(
          client.link.v1.credentials[":id"].$get({ param: { id: credentialId } }),
        );

        if (result.ok) {
          const { provider } = result.data;
          chat.sendMessage({
            parts: [{ type: "data-credential-linked", data: { provider, displayName: provider } }],
          });
        }
      } catch (error) {
        console.error("Failed to fetch credential details:", error);
      } finally {
        // Clean URL params
        url.searchParams.delete("credential_id");
        window.history.replaceState({}, "", url.toString());
      }
    }
  }

  beforeNavigate((navigation) => {
    if (navigation.type === "goto") return;
    showContents = false;
    // Abort active stream to free HTTP connection for the new page's loader.
    // Without this, browser connection limits (6 per origin in HTTP/1.1) cause
    // the navigation to block until the stream completes.
    chat.stop();
    // Also abort any pending resumeStream GET request (ai-sdk doesn't handle this)
    resumeAbortController?.abort();
    resumeAbortController = null;
  });

  afterNavigate(() => {
    setup();
    reconnect();
  });

  // Handle OAuth return flow on initial mount
  onMount(() => {
    setup();
    reconnect();
  });

  /**
   * Stop handler - calls DELETE endpoint to abort server-side stream, then stops client
   */
  async function handleStop() {
    trackEvent(GA4.STREAM_STOP);
    await fetch(`${getAtlasDaemonUrl()}/api/chat/${chatId}/stream`, { method: "DELETE" }).catch(
      () => {},
    );
    chat.stop();
  }

  let showCatalog = $state(false);
</script>

<div class="chat" class:visible={showContents}>
  <div class="main">
    <div class="messages" bind:this={scrollContainer}>
      <div class="messages-container">
        <div class="messages-inner">
          <div class="first-message">
            <p>{title}</p>
          </div>
        </div>
      </div>

      <div
        class="interactive-container"
        role="region"
        aria-label="Drag and drop files to attach them to your conversation"
        class:has-outline={chat.messages?.some((msg) =>
          msg.parts.some((part) => part.type === "data-outline-update"),
        )}
        ondragover={(e) => e.preventDefault()}
        ondrop={(e) => {
          e.preventDefault();
          handleFileDrop(appCtx, Array.from(e.dataTransfer?.files ?? []), chatId);
        }}
      >
        <div class="interactive-container-int">
          <MessageForm
            {chatId}
            isDisabled={Array.from(appCtx.stagedFiles.state.values()).some((f) =>
              isFileInProgress(f),
            )}
            bind:message
            onSubmit={(message) => {
              // Check if still uploading
              const hasUploadingFiles = Array.from(appCtx.stagedFiles.state.values()).some((f) =>
                isFileInProgress(f),
              );

              if (hasUploadingFiles) return;

              if (chat && message.trim()) {
                const readyFiles = Array.from(appCtx.stagedFiles.state.values()).filter(
                  (f) => f.status === "ready" && f.artifactId,
                );

                trackEvent(GA4.MESSAGE_SEND, { is_new: true });

                if (readyFiles.length > 0) {
                  // Send message with text AND artifact-attached data part
                  // The parts array includes both the user's text and the artifact metadata
                  chat.sendMessage({
                    parts: [
                      { type: "text", text: message },
                      {
                        type: "data-artifact-attached",
                        data: {
                          artifactIds: readyFiles
                            .map((f) => f.artifactId)
                            .filter((f) => f !== undefined),
                          filenames: readyFiles.map((f) => f.name),
                        },
                      },
                    ],
                  });
                } else {
                  // No attachments, send simple text message
                  chat.sendMessage({ text: message });
                }
                message = "";
                appCtx.stagedFiles.clear();
              }
            }}
            status={chat.status}
            onStop={async () => {
              await handleStop();
            }}
          />
        </div>
      </div>

      <div class="catalog">
        <button
          type="button"
          class="explore"
          onclick={() => {
            showCatalog = !showCatalog;
          }}
        >
          <Icons.Search />
          {showCatalog ? "Hide Catalog" : "Explore Ideas"}
        </button>

        {#if showCatalog}
          <div transition:fade={{ duration: 200 }}>
            <Catalog
              onclick={(item) => {
                message = item.prompt;

                if (scrollContainer) {
                  scrollContainer.scrollTop = 0;
                }
              }}
            />
          </div>
        {/if}
      </div>

      <ChatBufferBlur />
    </div>
  </div>
</div>

<style>
  .chat {
    block-size: 100%;
    display: grid;
    grid-template-columns: 1fr;
    inline-size: 100%;
    overflow: hidden;
    position: relative;
    opacity: 0;
    z-index: var(--layer-0);

    &.visible {
      opacity: 1;
    }
  }

  .main {
    display: flex;
    block-size: 100%;
    overflow: hidden;
    flex-direction: column;
    position: relative;
  }

  .first-message {
    p {
      font-size: var(--font-size-7);
      font-weight: var(--font-weight-5);
      text-align: center;
    }
  }

  .messages {
    block-size: 100%;
    display: flex;
    justify-content: center;
    flex-direction: column;
    overflow-y: scroll;
    padding-block: 0 var(--size-16);
    position: relative;
    scrollbar-width: thin;
    scroll-behavior: smooth;
  }

  .messages-container {
    grid-template-columns: 1fr;
    padding-block: var(--size-10) var(--size-4);
  }

  .messages-inner {
    display: flex;
    flex-direction: column;
    inline-size: 100%;
    gap: var(--size-8);
    margin: 0 auto;
    max-inline-size: var(--size-272);
    overflow: hidden;
    padding-inline: var(--size-16);
  }

  .interactive-container {
    --local__translate-y: var(--size-4);
    inset-block-end: var(--size-16);
    inset-inline-start: calc(var(--size-56));
    inset-inline-end: var(--size-1-5);
    position: fixed;
    transition: all 450ms ease-in-out;
    z-index: var(--layer-2);

    & {
      inline-size: 100%;
      position: sticky;
      inset-block-end: 0;
      inset-inline-start: unset;
      inset-inline-end: unset;
      margin-inline: auto;
      max-inline-size: var(--size-160);
      padding-inline: var(--size-8);
    }

    &.has-outline {
      inset-inline-end: calc(var(--size-56));

      & {
        --local__translate-x: calc(-1 * calc(var(--size-28) + var(--size-6)));
        transition: transform 450ms ease-in-out;
      }
    }

    .interactive-container-int {
      margin-inline: auto;
      max-inline-size: var(--size-160);
      padding-inline: var(--size-8);

      & {
        max-inline-size: unset;
        padding-inline: unset;
      }
    }
  }

  .catalog {
    position: relative;
    z-index: var(--layer-2);
  }

  .explore {
    align-items: center;
    border: var(--size-px) solid var(--color-border-1);
    block-size: var(--size-8);
    border-radius: var(--radius-round);
    display: flex block;
    gap: var(--size-1-5);
    padding-inline: var(--size-3) var(--size-4);
    font-size: var(--font-size-4);
    font-weight: var(--font-weight-5);
    margin-block: var(--size-8);
    margin-inline: auto;
    transition: all 0.2s ease;

    & :global(svg) {
      opacity: 0.6;
    }

    &:hover {
      background-color: var(--color-highlight-1);
      border-color: transparent;
    }
  }
</style>
