import { building } from "$app/environment";
import type { Handle } from "@sveltejs/kit";
import process from "node:process";
import { parse } from "node-html-parser";

/**
 * Inject `window.__FRIDAY_CONFIG__` into served HTML in dev so the same
 * runtime-config mechanism works without `import.meta.env.VITE_*` reads.
 * In production the playground ships as a `deno compile`'d binary that
 * runs `static-server.ts`, which performs the same injection at request
 * time using the launcher's process env. This hook only runs under
 * `vite dev` and during SvelteKit's prerender pass; in adapter-static
 * production it's not in the bundle.
 *
 * Uses node-html-parser (same lib applications/frame uses for CSP nonce
 * injection) to do a real DOM insertion instead of regex-replacing
 * `</head>`. The `<` → `<` escape on the JSON payload is the
 * OWASP-recommended encoding for inline JSON.
 */
const config: Record<string, string> = {};
if (process.env.EXTERNAL_DAEMON_URL) config.externalDaemonUrl = process.env.EXTERNAL_DAEMON_URL;
if (process.env.EXTERNAL_TUNNEL_URL) config.externalTunnelUrl = process.env.EXTERNAL_TUNNEL_URL;

// Skip injection during `vite build` (the prerender pass) AND when no
// config is set. Production HTML is generated by adapter-static during
// build; the launcher's runtime env isn't available then, and any value
// we'd inject would just be overwritten by static-server.ts at serve
// time. Leaving the static HTML untouched keeps static-server.ts the
// sole injection point in the compiled binary.
const shouldInject = !building && Object.keys(config).length > 0;
const configJson = JSON.stringify(config).replace(/</g, "\\u003c");
const configScript = `<script>window.__FRIDAY_CONFIG__=${configJson};</script>`;

function injectConfig(html: string): string {
	const root = parse(html);
	const head = root.querySelector("head");
	if (!head) return html;
	head.appendChild(parse(configScript));
	return root.toString();
}

export const handle: Handle = ({ event, resolve }) =>
	resolve(event, {
		transformPageChunk: ({ html, done }) => {
			// `done` flips true on the final chunk — only the final chunk
			// contains the closing `</head>` we need to insert before.
			if (!shouldInject || !done) return html;
			return injectConfig(html);
		},
	});
