import { building } from "$app/environment";
import type { Handle } from "@sveltejs/kit";
import process from "node:process";

/**
 * Inject `window.__FRIDAY_CONFIG__` into served HTML in dev so the same
 * runtime-config mechanism works without `import.meta.env.VITE_*` reads.
 * In production the playground ships as a `deno compile`'d binary that
 * runs `static-server.ts`, which performs the same injection at request
 * time using the launcher's process env. This hook only runs under
 * `vite dev` and during SvelteKit's prerender pass; in adapter-static
 * production it's not in the bundle.
 *
 * `transformPageChunk` is SvelteKit's documented hook for response-HTML
 * mutation — `transformIndexHtml` (Vite's plugin API) is bypassed by
 * SvelteKit's dev request handler.
 */
const config: Record<string, string> = {};
if (process.env.EXTERNAL_DAEMON_URL) config.externalDaemonUrl = process.env.EXTERNAL_DAEMON_URL;
if (process.env.EXTERNAL_TUNNEL_URL) config.externalTunnelUrl = process.env.EXTERNAL_TUNNEL_URL;

// Skip injection during `vite build` (the prerender pass) AND when no
// config is set. Production HTML is generated by adapter-static during
// build; the launcher's runtime env isn't available then, and any value
// we'd inject would just be overwritten by static-server.ts at serve
// time. Leaving the static HTML untouched keeps static-server.ts the
// sole injection point in the compiled binary.
const shouldInject = !building && Object.keys(config).length > 0;
// Escape `</` so a URL containing `</script>` can't break the inline tag.
const configJson = JSON.stringify(config).replace(/<\/(script)/gi, "<\\/$1");
const configTag = `<script>window.__FRIDAY_CONFIG__=${configJson};</script>`;

export const handle: Handle = ({ event, resolve }) =>
	resolve(event, {
		transformPageChunk: ({ html, done }) => {
			if (!shouldInject || !done) return html;
			return html.includes("</head>") ? html.replace("</head>", `${configTag}</head>`) : html;
		},
	});
