// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CypherKeyset struct {
	ID        string             `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"userId"`
	KeySet    []byte             `db:"key_set" json:"keySet"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
