// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"
)

const createKeyset = `-- name: CreateKeyset :one
INSERT INTO cypher.keyset (user_id, key_set)
VALUES ($1, $2)
RETURNING id, user_id, key_set, created_at, updated_at
`

type CreateKeysetParams struct {
	UserID string `db:"user_id" json:"userId"`
	KeySet []byte `db:"key_set" json:"keySet"`
}

// CreateKeyset
//
//	INSERT INTO cypher.keyset (user_id, key_set)
//	VALUES ($1, $2)
//	RETURNING id, user_id, key_set, created_at, updated_at
func (q *Queries) CreateKeyset(ctx context.Context, arg *CreateKeysetParams) (*CypherKeyset, error) {
	row := q.db.QueryRow(ctx, createKeyset, arg.UserID, arg.KeySet)
	var i CypherKeyset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeySet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getKeysetByUserID = `-- name: GetKeysetByUserID :one
SELECT id, user_id, key_set, created_at, updated_at FROM cypher.keyset WHERE user_id = $1
`

// GetKeysetByUserID
//
//	SELECT id, user_id, key_set, created_at, updated_at FROM cypher.keyset WHERE user_id = $1
func (q *Queries) GetKeysetByUserID(ctx context.Context, userID string) (*CypherKeyset, error) {
	row := q.db.QueryRow(ctx, getKeysetByUserID, userID)
	var i CypherKeyset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeySet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
