name: "atlas-operator: Publish Docker Image"

on:
  push:
    branches:
      - main
    paths:
      - "apps/atlas-operator/**"

env:
  GAR_LOCATION: us-west2
  PROJECT_NAME: tempest-sandbox
  REPOSITORY: atlas-operator
  ENVIRONMENT: sandbox

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        id: build-image
        run: |
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY:$GITHUB_SHA" \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            ./apps/atlas-operator
          echo "image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY:$GITHUB_SHA" >> "$GITHUB_OUTPUT"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          project_id: ${{ env.PROJECT_NAME }}
          workload_identity_provider: "projects/415092695556/locations/global/workloadIdentityPools/github/providers/atlas-operator"
          service_account: "github-atlas-operator-ci@tempest-sandbox.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Docker configuration
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Push image
        run: |
          docker push -a "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY"

      - name: Fetch tempest-kustomize repository
        uses: actions/checkout@v6
        with:
          repository: tempestteam/tempest-kustomize
          token: ${{ secrets.PAT }}
          path: tempest-kustomize-repository
          fetch-depth: 1

      - name: Update manifest file image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '(.spec.template.spec.containers[] | select(.name == "manager").image) = "us-west2-docker.pkg.dev/${{ env.PROJECT_NAME }}/atlas-operator/atlas-operator:${{ github.sha }}"' 'tempest-kustomize-repository/atlas-operator/overlays/${{ env.ENVIRONMENT }}/deployment.yaml'

      - name: Setup tempest-kustomize Repository
        working-directory: tempest-kustomize-repository
        run: |
          git fetch origin main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url --push origin https://github.com/tempestteam/tempest-kustomize.git
          git checkout -b release-atlas-operator-${{ github.sha }}

      - name: Commit
        working-directory: tempest-kustomize-repository
        run: |
          git add .
          git commit -m "Release atlas-operator-${{ github.sha }}"
          git push origin HEAD

      - name: Create PR && merge
        working-directory: tempest-kustomize-repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr create -B main -H release-atlas-operator-${{ github.sha }} -t "deploy-atlas-operator-${{ github.sha }}" -b ""
          command="gh pr merge release-atlas-operator-${{ github.sha }} --squash --admin"
          max_retries=30
          delay=2
          retry_count=0
          until $command; do ((retry_count++)); [ "$retry_count" -ge "$max_retries" ] && echo "Failed after $max_retries attempts." && break; echo "Retrying in $delay seconds..."; sleep $delay; done; [ "$retry_count" -lt "$max_retries" ] && echo "Command succeeded." || echo "Command failed after maximum retries."
