name: atlas-traefik-docker

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  GAR_LOCATION: us-west2
  PROJECT_NAME: ${{ secrets.GCP_PROJECT }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: atlas
  IMAGE_NAME: traefik

permissions:
  contents: read
  id-token: write

jobs:
  build-publish:
    name: Build and Publish atlas-traefik
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker Image
        id: build-image
        run: |-
          docker build \
            -f apps/traefik/Dockerfile \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA" \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME:latest" \
          .
          echo "image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA" >> "$GITHUB_OUTPUT"

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: "projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/atlas-github"

      - name: Docker configuration
        run: |-
          echo ${{ steps.auth.outputs.auth_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Push image to sandbox
        run: |-
          docker push -a "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME"

      - name: Push image to production
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |-
          docker tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA" "$GAR_LOCATION-docker.pkg.dev/tempest-production/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
          docker push "$GAR_LOCATION-docker.pkg.dev/tempest-production/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
