name: atlas-cd

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  GAR_LOCATION: us-west2
  PROJECT_NAME: ${{ secrets.GCP_PROJECT }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: atlas

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        id: build-image
        run: |-
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY:$GITHUB_SHA" \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
          .
          echo "image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY:$GITHUB_SHA" >> "$GITHUB_OUTPUT"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: "projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/atlas-github"

      - name: Docker configuration
        run: |-
          echo ${{ steps.auth.outputs.auth_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Push image
        run: |-
          docker push -a "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/$REPOSITORY"

      - name: Fetch tempest-kustomize repository
        uses: actions/checkout@v4
        with:
          repository: tempestteam/tempest-kustomize
          token: ${{ secrets.PAT }}
          path: tempest-kustomize-repository
          fetch-depth: 1

      - name: Update manifest file image tag for atlas
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.spec.template.spec.containers[0].image |= "${{ steps.build-image.outputs.image }}"' 'tempest-kustomize-repository/atlas/overlays/sandbox/deployment.yaml'

      - name: Setup tempest-kustomize Repository
        working-directory: tempest-kustomize-repository
        run: |
          git fetch origin main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url --push origin https://github.com/tempestteam/tempest-kustomize.git
          git checkout -b release-atlas-${{ github.sha }}

      - name: Commit
        working-directory: tempest-kustomize-repository
        run: |
          git add .
          git commit -m "Release atlas-${{ github.sha }}"
          git push origin HEAD

      - name: Create PR && merge
        working-directory: tempest-kustomize-repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr create -B main -H release-atlas-${{ github.sha }} -t "deploy-atlas-${{ github.sha }}" -b ""
          command="gh pr merge release-atlas-${{ github.sha }} --squash --admin"
          max_retries=30
          delay=2
          retry_count=0
          until $command; do ((retry_count++)); [ "$retry_count" -ge "$max_retries" ] && echo "Failed after $max_retries attempts." && break; echo "Retrying in $delay seconds..."; sleep $delay; done; [ "$retry_count" -lt "$max_retries" ] && echo "Command succeeded." || echo "Command failed after maximum retries."
