name: supabase

on:
  pull_request:
    paths:
      - 'supabase/**'
  merge_group:

permissions:
  pull-requests: read
  contents: read

jobs:
  supabase:
    name: supabase migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase db start
      - run: supabase test db
