name: Web Client Lint

on:
  pull_request:
    paths:
      - "apps/web-client/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.6.4

      - name: Install dependencies
        run: deno install

      - name: Run ESLint
        run: deno task eslint
        working-directory: apps/web-client
